SUSE/doc-sleha

xml/ha_config_cli.xml, xml/ha_storage_protection.xml
=> Fix some typo in the SLE HA doc

xml/ha_drbd.xml
Sorry for not creating files on my local environment first, please help to review.
=> fix bsc#975589: change command of checking status and disable service.

xml/art_sle_ha_install_quick.xml, xml/phrases-decl.ent
Changes:
* Shorten abstract, move last two paragraphs into "Usage Scenario"
* Add new workflow section
* Add missing description for FC (beneath FCoE and iSCSI)
* Mention ha-cluster-init takes care for Time Synchronization and SSH
* Enhance note for "Installing Software Packages on All Parties"
* Remove obsolete, commented section
* Add note about Softdog not supported
* Use /etc/modules-load.d/watchdog.conf instead of /etc/modules-load.d/softdog.conf
* Remove some substeps
* Move note about "Secure Passwords"
* Add short description about "Split Brain Resolution via SBD" from Lars
* Add additional remarks and comments for SP3
* split-brain -> split brain
=> Add feedback from Kai & Lars

xml/art_sle_ha_nfs_quick.xml, xml/phrases-decl.ent
@tomschr : Here my suggestions, there were also some sentences that I could not make sense of, please also search for remarks with "taroth" to find all issues. Thanks!
=> comments by taroth

xml/art_sle_ha_pmremote.xml
Some minor issues found with the guide.
=> Pacemaker Remote: Issues with configuration

xml/art_sle_ha_pmremote.xml
Overall this looks good, and is well-written :dancers:
I'm not sure how to handle the references to other manual, see line 292 ' Installation and Setup Quick Start' and line 551 'See the section Rolling Upgrade'. But I see your comments, so I guess you know what  to do :)
=> Proofread & tweaks

xml/art_sle_ha_install_quick.xml
@renzhengeek , @liu4480 - please review and add comments here on GH in case I did not understand correctly. Thanks!
=> starting/stopping SBD with systemctl (bsc#1067310)

xml/ha_docupdates.xml, xml/ha_ocfs2.xml
add support statement for OCFS2 (as part of bsc#1074694)
=> suggest fix for bsc#1074694

xml/art_sle_ha_geo_quick.xml, xml/art_sle_ha_install_quick.xml, xml/ha_requirements.xml, xml/phrases-decl.ent
@aginies : Please review (before I transfer this to the 'Installation and Setup Quick Start' and the 'Geo Quick Start') .
=> mention required modules, patterns, and syste roles

xml/art_sle_ha_geo_quick.xml, xml/geo_manage_i.xml, xml/phrases-decl.ent
=> [WIP] Feature/geo manual tickets

xml/ha_ocfs2.xml
=> fixes bsc#bsc_1088623

xml/ha_storage_protection.xml, xml/phrases-decl.ent
* Migrate sect2 -> sect1
* Requirements ID=sec.ha.storage.protect.req
* Number of SBD Devices ID=sec.ha.storage.protect.fencing.number
* Improve section structure
* Introduce new section Setting Up the Hardware Watchdog, ID=sec.ha.storage.protect.hw-watchdog
* Move section with ID=sec.ha.storage.protect.sw-watchdog from sect3 -> sect2
* Move section with ID=sec.ha.storage.protect.watchdog.timings as the last child
* Improve steps in procedure pro.ha.storage.protect.sw-watchdog
* Some steps are about testing SBD; remove them as these are
already documented later
* Amend steps to test if the watchdog module is loaded correctly
* Add some remarks for Tanja
---
@taroth21
The changes are so big that it probably doesn't make sense to comment on each line. …
=> Restructure SBD chapter

xml/ha_storage_protection.xml
Title: Additional Mechanisms for Storage Protection
* Change content of sg_persist
* Add remarks for developers
* Add introducery paragraph
* Add additional check if the disk supports persistent
reservations
* Combine the two procedure into one; move para inbetween
to the end
* Correct sect1 -> sect2
---
Remaining ToDos:
=> Create new section "Additional Mechanisms for Storage Protection"

xml/ha_storage_protection.xml
This fixes bsc#1074038
@gao-yan: Can you have a look at this PR too? Thanks! 
[cha.ha.storage.protect_color_en.pdf](https://github.com/SUSE/doc-sleha/files/1950904/cha.ha.storage.protect_color_en.pdf)
=> bsc1074038: Document SBD_DELAY_START variable

xml/art_sle_ha_nfs_quick.xml, xml/common_intro_making_i.xml, xml/ha_acl.xml, xml/ha_cluster_md.xml, xml/ha_concepts.xml, xml/ha_config_basics.xml, xml/ha_config_cli.xml, xml/ha_drbd.xml, xml/ha_fencing.xml, xml/ha_gfs2.xml, xml/ha_glossary.xml, xml/ha_hawk2_cons_i.xml, xml/ha_lb_lvs.xml, xml/ha_loadbalancing.xml, xml/ha_management.xml, xml/ha_netbonding.xml, xml/ha_ocfs2.xml, xml/ha_rear.xml, xml/ha_requirements.xml, xml/ha_samba.xml, xml/ha_storage_protection.xml, xml/ha_troubleshooting.xml, xml/ha_yast_cluster.xml
* linkcheck was ok, so no changes
* spell check
* style check
Although stylechecker showed some problems with sentence length, I hardly changed them and leave most of them as they were. 
Feel free to disagree with some changes. :wink:
=> Spell and style check

xml/ha_concepts.xml
* correct term: server(s) -> node(s)
* Add missing description from bsc#1049388
@taroth21 If you have time, I'd appreciate your review. :wink: Thanks!
=> Add missing description from bsc#1049388

xml/ha_cluster_lvm.xml, xml/ha_migration.xml
This is still WIP and needs further work and a sanity check on Monday. Gang and Guoqing: 
Thank you very much for the well-structured and profound input! :)
Two commands did not seem to go with an explanation (see the two FIXMEs in the text). Could you provide  an explanation for those two command, too, please? 
ToDos (on my side):
=> migrate mirror logical volume to Cluster MD

xml/book_sle_ha_guide.xml, xml/entity-decl.ent, xml/ha_cluster_lvm.xml, xml/ha_cluster_md.xml, xml/ha_config_example.xml, xml/ha_gfs2.xml, xml/ha_glossary.xml, xml/ha_intro.xml, xml/ha_migration.xml, xml/ha_ocfs2.xml, xml/ha_samba.xml, xml/ha_storage_basics.xml
@zzhou1 and team: please review and comment.
I have added a new chapter about DLM as a start:
- it covers general information about LVM (which was distributed across several chapters beforehand)
- it appears at the beginning of the 'Storage and Data Replication' part
- it covers the information from bsc#1089339c#4
- it contains a procedure on how to configure a resource (group) for DLM (moved from OCFS2/GFS2 chapter)
- the chapters about OFCS2, GFS2, cluster LVM, and cluster MD contain a pointer to the resource configuration for DLM
For the next revision of code 15 (SP1), we will also double-check the  OFCS2, GFS2, cluster LVM and cluster MD chapters for any more common info that could be moved to this chapter (so it might be renamed again if there should be more to cover apart from DLM).
=> [Do not merge yet] Feature/bsc 1089339 sctp dlm

xml/ha_config_basics.xml, xml/ha_requirements.xml
* Introduce section "Quorum Calculation"
* Carve out difference between 2-node and n-node clusters
* Add Corosync excerpt of config for 2-node cluster
* <s>TODO: Amed section "sec.ha.config.basics.corosync.n-node" about n-node clusters</s>
=> WIP: Integrate bsc#1088466

xml/ha_drbd.xml
* Add new section (ID=sec.ha.drbd.fencing) with example of `net` and `handlers` section in DRBD config file
=> Fix 1095374: Resource-level fencing using CIB

xml/ha_clvm.xml
* Remove note "Create Cluster Resources First"
* Change order between sections id=sec.ha.clvm.config.resources (Creating the Cluster Resources) and section id=sec.ha.clvm.config.cmirrord (Configuring Cmirrord)
* Correct title of section id=sec.ha.clvm.config.cmirrord from "Configuring Cmirrord" to "Scenario: Configuring Cmirrord"
=> Fix bsc#1054479

xml/ha_fencing.xml
@nick-wang: Could you please have a look and let me know if it's ok? Then I would merge the changes into the other branches, too (like you mentioned in bsc#1118238 ). Thanks!
=> Feature/kdump bsc#1118238

xml/ha_cluster_lvm.xml
=> clvm2clusterMD_migration_bsc#1123496

xml/ha_cluster_lvm.xml
@GuoqingJiang : Please have a look (I also sent you a mail with two more questions a few minutes ago). Many thanks!
=> more details on data-offset (follow-up on bsc#1123496)

xml/art_sle_ha_pmremote.xml, xml/entity-decl.ent, xml/ha_concepts.xml, xml/ha_fencing.xml, xml/ha_glossary.xml, xml/ha_hawk2_history_i.xml, xml/ha_troubleshooting.xml
(as listed in https://wiki.clusterlabs.org/wiki/Pacemaker_2.0_Daemon_Changes).
@tomschr @gao-yan: Please review, this needs to be merged within the next days to be included in the translation drop.
=> change names of pacemaker 2.0 daemons

xml/ha_concepts.xml, xml/ha_config_basics.xml, xml/ha_glossary.xml, xml/ha_hawk2_history_i.xml
- based on
https://clusterlabs.org/pacemaker/doc/en-US/Pacemaker/2.0/html/Pacemaker_Explained/_cluster_architecture.html
- rest (Process Flow section) is still TBD
Do not merge yet!
=> [WIP] rewrite description of architecture

xml/MAIN.SLEHA.xml, xml/art_sle_ha_geo_quick.xml, xml/art_sle_ha_install_quick.xml, xml/art_sle_ha_nfs_quick.xml, xml/art_sle_ha_pmremote.xml, xml/book_sle_ha_geo.xml, xml/entity-decl.ent
Needs some test runs regarding the recent updates, please do not merge yet.
=> [WIP] Feature/prepare docstart

README.adoc
Migrated to master (origin from #109)
=> Prepare for develop -> master migration

xml/art_sle_ha_install_quick.xml
=> Install Quick: fixed typo

xml/ha_cluster_lvm.xml, xml/ha_migration.xml
Fix for bsc#1139551 - Offline migration from SLE12-SP4 to SLE15-SP1.
=> Bugfix/offline migr bsc#1139551

xml/art_sle_ha_geo_quick.xml, xml/art_sle_ha_install_quick.xml, xml/art_sle_ha_pmremote.xml, xml/book_sle_ha_geo.xml, xml/common_intro_available_doc_i.xml, xml/common_intro_feedback_i.xml, xml/entity-decl.ent, xml/geo_booth_i.xml, xml/geo_drbd_i.xml, xml/geo_install_i.xml, xml/geo_ip_i.xml, xml/geo_manage_hawk2_i.xml, xml/geo_more_i.xml, xml/geo_resources_i.xml, xml/geo_upgrade_i.xml, xml/ha_acl.xml, xml/ha_clvm.xml, xml/ha_geocluster.xml, xml/ha_install.xml, xml/ha_installation.xml, xml/ha_intro.xml, xml/ha_migration.xml, xml/ha_rear.xml, xml/phrases-decl.ent
For SLE Ha 12 SP5 only:
new documentation.suse.com URLs
=> update doc URLs

xml/art_sle_ha_install_quick.xml, xml/entity-decl.ent
* Add entities for `test.script`/`cmd.test.script`
* Split section "sec-ha-inst-quick-test" into two sect2's.
See https://jira.suse.com/browse/SLE-10768
*Are backports required?* needs to be checked
=> SLE-10768: Work on ha-cluster-preflight-check

xml/ha_config_cli.xml
Contains a new section to describe how to stop cluster resources
Related to https://trello.com/c/ekDPTh8U
=> Add missing section to stop resources ("crm stop")

xml/ha_migration.xml
Fix FATE#325878
Unclear:
-----
5.2.4 Rolling Upgrade
=> Upgrade cluster w/ install of SP

xml/geo_more_i.xml
Integrate proofreading changes from Dublin check of SLE-HA GeoClustering Quick Start Guide
=> Integrate changes from Dublin proofreading of GeoCluster QS

xml/ha_glossary.xml
Try to define the term "cluster stack". It's a small change, but could probably be helpful.
Darios definition sounded clear and useful to me, so I took it.
From https://trello.com/c/1m7jaHDe
This definition would probably useful for other releases as well:
=> Try to define "cluster stack"

xml/common_intro_lifecycle_support_i.xml
Add changes requested by proofreaders in Dublin. (Just 2 lines in common_intro_lifecycle_support_i.xml)
=> Add Dublin proofreading changes to Admin Guide

xml/ha_migration.xml
Fix https://bugzilla.suse.com/show_bug.cgi?id=1174719 (and https://bugzilla.suse.com/show_bug.cgi?id=1139551)
=> Bugfix/upgrade paths bsc#1174719

xml/book_sle_ha_guide.xml, xml/ha_cluster_lvm.xml, xml/ha_config_basics.xml, xml/ha_config_cli.xml
Remove remaining occurrences of cLVM/clvm from Code-15-related docs (see comment by zzhou in SLE-10216).
Add a few sentences describing the overall goals of this pull request.
If there are relevant Bugzilla or Jira entries, reference them.
=> clvm/cLVM -> lvmlockd (related to SLE-10216)

xml/art_sle_ha_geo_quick.xml, xml/common_copyright_quick.xml, xml/common_gfdl1.2_i.xml, xml/common_legal.xml, xml/geo_booth_i.xml, xml/geo_challenges_i.xml, xml/geo_concept_i.xml, xml/geo_ip_i.xml, xml/geo_manage_hawk2_i.xml, xml/geo_manage_i.xml, xml/geo_more_i.xml, xml/geo_requirements_i.xml, xml/geo_resources_i.xml, xml/geo_sync_i.xml, xml/geo_upgrade_i.xml
* The new capitalization rules are documented at https://documentation.suse.com/style/current/single-html/docu_styleguide/#sec-capitalization, read carefully
* This is the result of an automatic conversion and will most likely need further adjustments
* Make sure to review the entire diff
* Entity files have not been changed and need to be updated manually
* Some product/project names may have been inadvertently changed to the wrong capitalization
* Some titles may have been missed, either because they're split across multiple source lines or because of improper markup
* Update the conversion commit and remove the (WIP) from the commit message before merging
* This is the third PR in a series of four PRs
=> Update SLE-HA Geo guides to sentence case (WIP)

xml/copyright_techguides_quick.xml, xml/geo_docupdates.xml, xml/geo_drbd_i.xml, xml/geo_geostore_i.xml, xml/geo_overview_i.xml, xml/geo_scenario_i.xml, xml/geo_scripts_i.xml, xml/ha_config_example.xml, xml/ha_docupdates.xml, xml/ha_example.xml, xml/ha_example_cli_i.xml, xml/ha_example_gui_i.xml, xml/ha_hawk2_maintenance_i.xml, xml/nfs_quick_clusterscript.xml
* **The files in this PR are apparently not referenced in the documentation currently. It might make sense to decline this PR and simply delete the files from the repo instead.**
* The new capitalization rules are documented at https://documentation.suse.com/style/current/single-html/docu_styleguide/#sec-capitalization, read carefully
* This is the result of an automatic conversion and will most likely need further adjustments
* Make sure to review the entire diff
* Entity files have not been changed and need to be updated manually
* Some product/project names may have been inadvertently changed to the wrong capitalization
* Some titles may have been missed, either because they're split across multiple source lines or because of improper markup
* Update the conversion commit and remove …
=> Update unreferenced leftovers to sentence case (WIP)

xml/art_sle_ha_install_quick.xml, xml/art_sle_ha_nfs_quick.xml, xml/art_sle_ha_pmremote.xml
* The new capitalization rules are documented at https://documentation.suse.com/style/current/single-html/docu_styleguide/#sec-capitalization, read carefully
* This is the result of an automatic conversion and will most likely need further adjustments
* Make sure to review the entire diff
* Entity files have not been changed and need to be updated manually
* Some product/project names may have been inadvertently changed to the wrong capitalization
* Some titles may have been missed, either because they're split across multiple source lines or because of improper markup
* Update the conversion commit and remove the (WIP) from the commit message before merging
* This is the second PR in a series of four PRs
=> Update SLE-HA Quick Start guides to sentence case (WIP)

xml/common_intro_available_doc_i.xml
Rework section about available docs as discussed in SLE sync writers call.
No.
=> Intro: rework available docs

xml/book_sle_ha_geo.xml, xml/geo_intro.xml, xml/ha_intro.xml
Streamline and shorten book intros, add intro where missing.
No.
=> streamline book intros

xml/common_intro_lifecycle_support_i.xml
Shorten the support info in our intros, remove duplicate information.
No.
=> Intro: Support section

.github/PULL_REQUEST_TEMPLATE.md
Just a small enhancement for our infrastructure environment on GitHub.
* Use "Backports" instead of checklist (improves clarity)
* Use XML comments to suppress needless remarks
no required
=> Correct PR template

xml/art_sle_ha_pmremote.xml, xml/geo_upgrade_i.xml, xml/ha_migration.xml, xml/ha_requirements.xml
We received a request by @gao-yan  to backport the terminology changes to Code 12.
=> [WIP] Backport Change in Upgrade Terminology to Code 12

xml/ha_samba.xml
Linkcheck and spellcheck done. No stylecheck this time because there have been only few additions since last time.
No backports needed (old link still redirects).
=> Admin Guide, Geo Guide, Install Quick: final checks

.travis.yml, DC-SLE-HA-administration, DC-SLE-HA-all, DC-SLE-HA-geo-clustering, DC-SLE-HA-geo-clustering-guide, DC-SLE-HA-installation, DC-SLE-HA-nfs-storage, DC-SLE-HA-pacemaker-remote
Adjust DC files for SLE* to use the new stylesheets (branding update).
jsc#SLE-15711
=> branding update: suse2013-ns -> suse2021-ns

xml/ha_migration.xml
Add upgrade path from 15 SP2 to 15 SP3. 
No backports required.
=> Upgrade chapter: add path SP2->SP3

xml/article_pacemaker_remote.xml, xml/common_intro_lifecycle_support_i.xml, xml/ha_acl.xml, xml/ha_cluster_md.xml, xml/ha_concepts.xml, xml/ha_config_basics.xml, xml/ha_config_hawk2.xml, xml/ha_drbd.xml, xml/ha_glossary.xml, xml/ha_maintenance.xml, xml/ha_migration.xml, xml/ha_ocfs2.xml, xml/ha_qdevice-qnetd.xml, xml/ha_rear.xml, xml/ha_requirements.xml, xml/ha_samba.xml, xml/ha_yast_cluster.xml, xml/phrases-decl.ent
=> Integrate Dublin proofreading corrections to Admin Guide

xml/ha_cluster_md.xml
https://bugzilla.suse.com/show_bug.cgi?id=1168482
https://jira.suse.com/browse/DOCTEAM-119
=> Disaster Recovery for Cluster MD (bsc#1168482)

xml/entity-decl.ent, xml/ha_concepts.xml
Add note about Geo clusters and SAP workloads.
https://bugzilla.suse.com/show_bug.cgi?id=1192769
=> Geo Clusters for SAP Workloads

xml/art_sle_ha_install_quick.xml, xml/ha_fencing.xml, xml/ha_storage_protection.xml
SEO: fix broken links. Will be done for each version separately so no backport needed
=> SEO fix broken links EN

xml/art_sle_ha_install_quick.xml, xml/ha_clvm.xml, xml/ha_fencing.xml, xml/ha_storage_protection.xml
SEO: fix broken links. Will be done for each version separately, therefore no backport needed
=> SEO fix links 12 SP5 EN

xml/common_intro_feedback_i.xml
The master branch is now the main branch. Fixed the README link in the Feedback section. It still worked, but we should update it anyway.
jsc#SLE-22017
=> Change master to main in common_intro_feedback_i

README.adoc
Fixed a couple of things that were out of date, and one broken bit of markup.
=> Update README with minor fixes

xml/ha_migration.xml
Added SP4 to the upgrade paths table and list. Is there anything else that needs to be done/would be nice to do for this? 
jsc#DOCTEAM-565
=> Add upgrade paths for SP4

DC-SLE-HA-administration, DC-SLE-HA-all, DC-SLE-HA-geo-clustering, DC-SLE-HA-geo-clustering-guide, DC-SLE-HA-installation, DC-SLE-HA-nfs-storage, DC-SLE-HA-pacemaker-remote
=> Use suse2022-ns stylesheets for SLEHA

xml/ha_config_basics.xml
SEO fix broken link  for SLE-HA 12 SP3
Changes will be done for each version separately, so no backport necessary
=> SEO fix links SLEHA12SP3

xml/ha_maintenance.xml
Clarified when to use maintenance mode. I'll need to be careful with the backports as there were some changes to this chapter. 
jsc#DOCTEAM-356
=> Clarify when to use maintenance mode

images/src/svg/webserver_groupresource_a.svg, xml/ha_concepts.xml, xml/ha_config_basics.xml, xml/ha_config_hawk2.xml, xml/ha_drbd.xml, xml/ha_ocfs2.xml, xml/ha_storage_protection.xml
Integrated proofing corrections for the Administration Guide from VT.
=> SLE-HA Administration proofing integration

xml/article_pacemaker_remote.xml, xml/geo_manage_i.xml
Ran link, style, and spell checks on the Priority 3 guides.
=> Prio 3 guide checks

xml/article_installation.xml, xml/entity-decl.ent
Changed `ha-cluster-preflight-check` to `crm cluster crash_test`.
Should resolve the following:
SLE-16863
DOCTEAM-494
SLE-18369
SLE-23735
BSC#1199644
BSC#1194846
=> Update cluster testing command and example

xml/article_installation.xml, xml/geo_resources_i.xml, xml/ha_config_basics.xml, xml/ha_install.xml, xml/ha_maintenance.xml, xml/ha_storage_protection.xml, xml/ha_yast_cluster.xml, xml/phrases-decl.ent
Changed "Pacemaker service" to "cluster services".
jsc#DOCTEAM-104
=> Pacemaker service -> cluster services

xml/article_installation.xml, xml/ha_requirements.xml
Added an item in the extra requirements section that only the primary IP address is supported.
DOCTEAM-182
BSC#1185920
=> Add primary IP address requirement

en/xml/art_sle_ha_geo_quick.xml, en/xml/art_sle_ha_install_quick.xml, en/xml/art_sle_ha_pmremote.xml, en/xml/common_intro_available_doc_i.xml, en/xml/geo_booth_i.xml, en/xml/geo_install_i.xml, en/xml/geo_ip_i.xml, en/xml/geo_more_i.xml, en/xml/geo_resources_i.xml, en/xml/ha_acl.xml, en/xml/ha_clvm.xml, en/xml/ha_migration.xml, en/xml/ha_rear.xml, ja/xml/ha_clvm.xml, zh_cn/xml/ha_clvm.xml, zh_tw/xml/ha_clvm.xml
SEO fix briken links with &dsc;
=> fix broken link &dsc;

xml/ha_storage_protection.xml
Added an extra driver to the table of common watchdog drivers. 
jsc#DOCTEAM-684
bsc#1201687
=> Add wdat_wdt to watchdog driver list

xml/article_nfs_storage.xml, xml/ha_drbd.xml
Needed to revert PR#237 as actually the path needs to be fixed in the product.
bsc#1201901
=> Revert "Change /usr/lib/drbd/ to /lib/drbd/ for fence script (#237)"

xml/ha_fencing.xml
Updated a kdump step to something that works a little better, and added some missing content from the step before it.
jsc#DOCTEAM-358
bsc#1188396
=> Update kdump steps

xml/MAIN.SLEHA.xml, xml/product-entities.ent
Bump product numbers by 1, adjust Bugzilla pointer in the docs for next SP.
`Main` branch only.
=> Adjust infrastructure for next SP

doc-kit.conf, xml/common_intro_feedback.xml, xml/generic-entities.ent
Include the changes to the feedback intro file (mention icons for Bugzilla/GH PR)
* jsc#DOCTEAM-804
I will open separate PRs per maintenance branch.
=> update files with doc-kit (Nov 2022, e433ecf)

doc-kit.conf, xml/common_intro_feedback.xml, xml/generic-entities.ent
Include the changes to the feedback intro file (mention icons for Bugzilla/GH PR)
* jsc#DOCTEAM-804
=> update files with doc-kit (Nov 2022, e433ecf) - 15SP4

doc-kit.conf, xml/common_intro_feedback.xml, xml/generic-entities.ent
Include the changes to the feedback intro file (mention icons for Bugzilla/GH PR)
* jsc#-DOCTEAM-804
=> update files with doc-kit (Nov 2022)

xml/ha_config_cli.xml
Added missing `meta promotable=true` reported by @gao-yan. 
N/A
- SLE-HA 15
- SLE-HA 12
=> Add missing promotable attribute

xml/article_installation.xml
Clarified that you need to enable softdog on each node. Seems obvious, but someone using a quickstart might not be aware.
* jsc#DOCTEAM-838
- SLE-HA 15
- SLE-HA 12
=> Clarify softdog section in quickstart

xml/ha_storage_protection.xml
The first step was the same as the first command in the second step. 
* bsc#...
* jsc#DOCTEAM-835
- SLE-HA 15
- SLE-HA 12
=> Fix duplicate step in admin guide softdog procedure

xml/ha_crmreport_passl.xml
See also #291. 15 SP4 and SP5 don't require that change, but I did still need to change the command to use sudo, since that is the whole point of the chapter. 
* bsc#1206167
* jsc#DOCTEAM-854
- SLE-HA 15
- SLE-HA 12
=> Use sudo for crm report

xml/article_geo_clustering.xml, xml/article_installation.xml
Added a Next Steps section to the quickstart. It's pretty minimal but I can always expand it later. 
* jsc#DOCTEAM-837
- SLE-HA 15
- SLE-HA 12
=> Add next steps section to quickstart

xml/ha_yast_cluster.xml
Even though it's repeating the section title, I'd rather be consistent within the chapter.
* bsc#1179006
- SLE-HA 15
- SLE-HA 12
=> Add procedure title to Configuring Csync2 with YaST

xml/article_installation.xml
Integrate the proofing corrections (proofing drop 2) for the Installation and Setup Quick Start.
=> Installation Quick: integrate proofing corrections

xml/article_geo_clustering.xml, xml/phrases-decl.ent
Geo Clustering Quick Start review before GMC.
=> Geo Clustering Quick Start review

images/src/svg/webserver_groupresource_a.svg, xml/ha_config_basics.xml, xml/ha_config_cli.xml, xml/ha_configuring_resources.xml, xml/ha_crmreport_passl.xml, xml/ha_hawk2_batch_i.xml, xml/ha_hawk2_health_i.xml, xml/ha_hawk2_history_i.xml, xml/ha_hawk2_monitor_i.xml, xml/ha_managing_resources.xml, xml/ha_migration.xml, xml/ha_remote_hosts.xml, xml/ha_resource_constraints.xml
Integrate proofing corrections for the Admin Guide from proofing drop 2
- SLE-HA 15
- SLE-HA 12
=> Admin Guide: integrate proofing corrections

xml/ha_config_basics.xml
Improvements based on comments by @gao-yan in PR #312. Thank you!
- SLE-HA 15
- SLE-HA 12
=> Update some wording in config basics chapter

xml/ha_resource_constraints.xml
A very minor change to clarify a misleading statement.
* jsc#DOCTEAM-979
- SLE-HA 15
- SLE-HA 12
=> Clarify colocation scores

xml/article_pacemaker_remote.xml, xml/geo_booth_i.xml, xml/geo_concept_i.xml, xml/geo_ip_i.xml, xml/geo_manage_hawk2_i.xml, xml/geo_manage_i.xml, xml/geo_requirements_i.xml, xml/geo_resources_i.xml, xml/geo_sync_i.xml, xml/geo_trouble_i.xml
Spelling and style checks for the Geo Clustering Guide and Pacemaker Remote guide (NFS guide got a style check as part if its overhaul).
* bsc#...
* jsc#...
- SLE-HA 15
- SLE-HA 12
=> Quality checks for priority 3 guides

xml/article_installation.xml, xml/article_nfs_storage.xml
Here is the NFS guide overhaul, with changes for 15 SP3. ~Once we're happy with these changes, I'll also apply them to 12 SP5.~ One step for 12 SP5 is a bit different, so I'll open a separate PR for 12 SP5. 
Changes for 15 SP3 are in separate commits from the changes cherry-picked from 15 SP4/5.
PDF: 
[article-nfs-storage_en.pdf](https://github.com/SUSE/doc-sleha/files/11620860/article-nfs-storage_en.pdf)
* bsc#1201271
* jsc#DOCTEAM-473
- SLE-HA 15
- SLE-HA 12
=> NFS overhaul (for 15 SP3)

xml/ha_clvm.xml
One link was dead and the other useless.
* bsc#1213815
* jsc#DOCTEAM-1078
- SLE-HA 15
- SLE-HA 12
=> Remove For More Information section from ha_clvm

xml/ha_cluster_lvm.xml
It just wasn't very useful. See also #343.
* bsc#1213815
* jsc#DOCTEAM-1078
- SLE-HA 15
- SLE-HA 12
=> Remove For More Information section from ha_cluster_lvm

xml/article_installation.xml, xml/ha_resource_constraints.xml
Changed settings can be seen in the crmsh log file.
* bsc#1158562
* jsc#DOCTEAM-143
- SLE-HA 15
- SLE-HA 12
=> Clarify that bootstrap settings may not be pacemaker defaults

xml/ha_storage_protection.xml
Added some more detail about this parameter, plus a link to the TID.
* bsc#1210435
* jsc#DOCTEAM-970
- SLE-HA 15
- SLE-HA 12
=> Add more detail about SBD_DELAY_START

xml/phrases-decl.ent
Updated the time synchronisation section to mention that cluster nodes should have the same timezone configured.
* bsc#1216665
* jsc#DOCTEAM-1136
- SLE-HA 15
- SLE-HA 12
=> Cluster nodes should have the same timezone configured

xml/ha_storage_protection.xml
By request, added the watchdog for LPAR on IBM Power.
* bsc#1217081
* jsc#DOCTEAM-1144
- SLE-HA 15
- SLE-HA 12
=> Add pseries-wdt to list of watchdogs

xml/article_pacemaker_remote.xml, xml/copyright_techguides.xml, xml/copyright_techguides_quick.xml, xml/geo_ip_i.xml, xml/geo_sync_i.xml, xml/ha_acl.xml, xml/ha_agents.xml, xml/ha_cluster_lvm.xml, xml/ha_config_basics.xml, xml/ha_config_cli.xml, xml/ha_config_hawk2.xml, xml/ha_configuring_resources.xml, xml/ha_docupdates.xml, xml/ha_drbd.xml, xml/ha_fencing.xml, xml/ha_hawk2_health_i.xml, xml/ha_hawk2_history_i.xml, xml/ha_lb_haproxy.xml, xml/ha_lb_lvs.xml, xml/ha_loadbalancing.xml, xml/ha_managing_resources.xml, xml/ha_ocfs2.xml, xml/ha_rear.xml, xml/ha_requirements.xml, xml/ha_resource_constraints.xml, xml/ha_samba.xml, xml/ha_troubleshooting.xml, xml/ha_yast_cluster.xml
Fix broken links and replace `http` by `https` protocol where feasible.
- see also https://github.com/SUSE/doc-sle/pull/1635 
- SLE-HA 15
=> Fix broken links

xml/ha_iscsi_for_sbd.xml
Added a suggestion for how to find which stable device name goes with which /dev/sdX name.
* jsc#DOCTEAM-1170
- SLE-HA 15
- SLE-HA 12
=> Add a tip about lsblk -o

xml/ha_storage_protection.xml
Changed `=` to `>=` to show that this is a minimum value.
* bsc#1218275
* jsc#DOCTEAM-1207
- SLE-HA 15
- SLE-HA 12
=> Clarify that the stonith-timeout formula is a minimum

xml/book_administration.xml, xml/ha_virtualization.xml
Added a chapter about configuring VMs for HA. I tested these procedures and everything seemed to work fine, though I only have a small test setup so can't say what would happen on a larger scale.
PDF: 
[cha-ha-virtualization_en.pdf](https://github.com/SUSE/doc-sleha/files/13914580/cha-ha-virtualization_en.pdf) **(updated 2024-01-12)**
* jsc#DOCTEAM-64
- SLE-HA 15
- SLE-HA 12
=> Add chapter for HA virtualization

xml/article_nfs_storage.xml
The updated resource-agents package for 15 SP6 includes improvements that impact the steps in the NFS guide. 
* jsc#PED-7425
- SLE-HA 15
- SLE-HA 12
=> Update NFS steps with RA improvements

xml/article_installation.xml
Part 1, for initial updates to quick starts for the installation media. Will include a link when I add more info to the Admin Guide.
* jsc#PED-7399
- SLE-HA 15
- SLE-HA 12
=> Update note to mention SSH agent forwarding

xml/article_geo_clustering.xml, xml/article_installation.xml, xml/ha_acl.xml, xml/ha_agents.xml, xml/ha_config_basics.xml, xml/ha_config_cli.xml, xml/ha_config_hawk2.xml, xml/ha_configuring_resources.xml, xml/ha_crmreport_passl.xml, xml/ha_drbd.xml, xml/ha_error_codes.xml, xml/ha_gfs2.xml, xml/ha_glossary.xml, xml/ha_iscsi_for_sbd.xml, xml/ha_maintenance.xml, xml/ha_management.xml, xml/ha_managing_resources.xml, xml/ha_migration.xml, xml/ha_monitoring_clusters.xml, xml/ha_ocfs2.xml, xml/ha_rear.xml, xml/ha_remote_hosts.xml, xml/ha_requirements.xml, xml/ha_resource_constraints.xml, xml/ha_samba.xml, xml/ha_storage_basics.xml, xml/ha_storage_protection.xml, xml/ha_troubleshooting.xml, xml/ha_virtualization.xml, xml/ha_yast_cluster.xml
Performed spelling, style, and link checks on the Admin Guide, Installation quickstart, and Geo-clustering quick start.
Link checker still shows one link as 403, but it works fine in my browser :shrug: 
- SLE-HA 15
- SLE-HA 12
=> 15 SP6 Priority 2 guide checks

xml/article_geo_clustering.xml, xml/article_installation.xml, xml/book_administration.xml
Metadata: add revhistory for 3 deliverables that will be handed over to localization with locdrop 2:
- Administration Guide
- Installation & Setup Quick Start
- Geo Clustering Quick Start 
[Link to internal page](https://confluence.suse.com/display/documentation/Adding+metadata+to+all+SUSE+documentation)
- SLE HA 15
=> metadata: revhistory for 3 deliverables (locdrop 2)

xml/ha_yast_cluster.xml
Integrate proofing corrections for the Administration Guide from proofing drop 2.
- SLE-HA 15
- SLE-HA 12
=> Administration Guide: Integrate proofing corrections

xml/article_installation.xml
Integrate proofing corrections for the Installation and Setup Quick Start from proofing drop 2.
- SLE-HA 15
- SLE-HA 12
=> Installation Quick Start: Integrate proofing corrections

xml/ha_yast_cluster.xml, xml/phrases-decl.ent
Add final fixes for the Installation and Setup Quick Start.
- SLE-HA 15
- SLE-HA 12
=> Installation and Setup QS: final fixes

xml/article_geo_clustering.xml
Add final fixes for the Geo Clustering Quick Start.
- SLE-HA 15
- SLE-HA 12
=> Geo Clustering QS: final fixes

xml/article_nfs_storage.xml, xml/article_pacemaker_remote.xml, xml/geo_booth_i.xml, xml/geo_ip_i.xml, xml/geo_manage_i.xml, xml/geo_resources_i.xml, xml/geo_sync_i.xml, xml/ha_acl.xml
Spelling, style, and link checks for Priority 3 guides.
While still unable to download an internal ISO, I did download the latest public beta ISO and check the screen shots for ALL guides. There were a couple of very minor changes, but nothing I deemed worth a new screen shot. I did, however, fix some procedures in the ACL chapter after noticing a difference between the UI and the steps. This was in the Admin Guide (prio 2), but is not critical so not something we need to loc-drop again. 
* bsc#...
* jsc#...
- SLE-HA 15
- SLE-HA 12
=> SP6 prio3 guide checks

xml/article_geo_clustering.xml, xml/article_installation.xml, xml/article_nfs_storage.xml, xml/article_pacemaker_remote.xml, xml/book_administration.xml, xml/book_geo_clustering.xml
Add metadata for all deliverables. Data copied from spreadsheet 'Product Docs Metadata per deliverable'.
* https://confluence.suse.com/x/f4GZW
- SLE-HA 15
- SLE-HA 12
=> add metadata for all deliverables (main)

xml/article_geo_clustering.xml, xml/article_installation.xml, xml/article_nfs_storage.xml, xml/article_pacemaker_remote.xml, xml/book_administration.xml, xml/book_geo_clustering.xml
See https://github.com/SUSE/doc-sleha/pull/384
- SLE-HA 15
=> Add metadata for 15 SP4

xml/article_geo_clustering.xml, xml/article_installation.xml, xml/article_nfs_storage.xml, xml/article_pacemaker_remote.xml, xml/book_administration.xml, xml/book_geo_clustering.xml
See https://github.com/SUSE/doc-sleha/pull/384 
- SLE-HA 15
=> Add metadata for 15 SP3

xml/art_sle_ha_geo_quick.xml, xml/art_sle_ha_install_quick.xml, xml/art_sle_ha_nfs_quick.xml, xml/art_sle_ha_pmremote.xml, xml/book_sle_ha_geo.xml, xml/book_sle_ha_guide.xml
See https://github.com/SUSE/doc-sleha/pull/384 
- SLE-HA 15
=> Add metadata 15 SP2

xml/art_sle_ha_geo_quick.xml, xml/art_sle_ha_install_quick.xml, xml/art_sle_ha_nfs_quick.xml, xml/art_sle_ha_pmremote.xml, xml/book_sle_ha_geo.xml, xml/book_sle_haguide.xml
See https://github.com/SUSE/doc-sleha/pull/384 
- SLE-HA 12
=> Add metadata 12 SP5

xml/ha_drbd.xml, xml/ha_maintenance.xml
Since SLE 12 there has been a simpler command for moving a cluster to maintenance mode.
* jsc#DOCTEAM-1477
- SLE-HA 15
- SLE-HA 12
=> Update maintenance mode commands

xml/ha_resource_constraints.xml
Added some CIB details for NodeUtilization. TBH this whole section could use an overhaul, but I'll do that for SLE 16.
* bsc#1226835
* jsc#DOCTEAM-1475
- SLE-HA 15
- SLE-HA 12
=> Add useful CIB tips for NodeUtilization

xml/ha_maintenance.xml
Added the command to bring a node online again after putting into standby mode and rebooting. 
* bsc#1228983
* jsc#DOCTEAM-1534
- SLE-HA 15
- SLE-HA 12
=> Add command to exit standby mode after reboot

xml/ha_rear.xml
Switched ebiso to xorriso. 
* bsc#1229430
* jsc#DOCTEAM-1538
- SLE-HA 15
- SLE-HA 12
=> Update ebiso to xorriso

l10n/sleha/ja-jp/xml/ha_maintenance.xml, l10n/sleha/zh-cn/xml/ha_maintenance.xml, l10n/sleha/zh-tw/xml/ha_maintenance.xml
PR creator: Description
Delivery of updated SLE-HA Admin guide for zh-cn, zh-tw, and ja-jp.
The guides have passed: 
- validation check
- optipng
- and visual spot check on PDFs
- no editurls contained
PR creator: Which product versions do the changes apply to?
- SLE-HA 15
- SLE-HA 12
=> admin guide locdrop2

l10n/sleha/de-de/xml/article_geo_clustering.xml, l10n/sleha/de-de/xml/article_installation.xml, l10n/sleha/es-es/xml/article_geo_clustering.xml, l10n/sleha/es-es/xml/article_installation.xml, l10n/sleha/fr-fr/xml/article_geo_clustering.xml, l10n/sleha/fr-fr/xml/article_installation.xml, l10n/sleha/it-it/xml/article_geo_clustering.xml, l10n/sleha/it-it/xml/article_installation.xml, l10n/sleha/ja-jp/xml/article_geo_clustering.xml, l10n/sleha/ja-jp/xml/article_installation.xml, l10n/sleha/ja-jp/xml/book_administration.xml, l10n/sleha/pt-br/xml/article_geo_clustering.xml, l10n/sleha/pt-br/xml/article_installation.xml, l10n/sleha/zh-cn/xml/article_geo_clustering.xml, l10n/sleha/zh-cn/xml/article_installation.xml, l10n/sleha/zh-cn/xml/article_nfs_storage.xml, l10n/sleha/zh-cn/xml/article_pacemaker_remote.xml, l10n/sleha/zh-cn/xml/book_administration.xml, l10n/sleha/zh-cn/xml/book_geo_clustering.xml, l10n/sleha/zh-tw/xml/article_geo_clustering.xml, l10n/sleha/zh-tw/xml/article_installation.xml, l10n/sleha/zh-tw/xml/book_administration.xml
Add missing localized metadata and correct some metadata strings that should not have been translated in the first place. 
- SLE-HA 15
=> Add missing localized metadata for SLE HA 15 SP6

l10n/sleha/de-de/xml/article_geo_clustering.xml, l10n/sleha/de-de/xml/article_installation.xml, l10n/sleha/es-es/xml/article_geo_clustering.xml, l10n/sleha/es-es/xml/article_installation.xml, l10n/sleha/fr-fr/xml/article_geo_clustering.xml, l10n/sleha/fr-fr/xml/article_installation.xml, l10n/sleha/it-it/xml/article_geo_clustering.xml, l10n/sleha/it-it/xml/article_installation.xml, l10n/sleha/ja-jp/xml/article_geo_clustering.xml, l10n/sleha/ja-jp/xml/article_installation.xml, l10n/sleha/ja-jp/xml/book_administration.xml, l10n/sleha/pt-br/xml/article_geo_clustering.xml, l10n/sleha/pt-br/xml/article_installation.xml, l10n/sleha/zh-cn/xml/article_geo_clustering.xml, l10n/sleha/zh-cn/xml/article_installation.xml, l10n/sleha/zh-cn/xml/article_nfs_storage.xml, l10n/sleha/zh-cn/xml/article_pacemaker_remote.xml, l10n/sleha/zh-cn/xml/book_administration.xml, l10n/sleha/zh-cn/xml/book_geo_clustering.xml, l10n/sleha/zh-tw/xml/article_geo_clustering.xml, l10n/sleha/zh-tw/xml/article_installation.xml, l10n/sleha/zh-tw/xml/book_administration.xml
1.  Add its namespace to root element
2.  Add localized metadata
- SLE-HA 15
=> Add localized metadata for SLE HA 15 SP4

l10n/sleha/de-de/xml/article_geo_clustering.xml, l10n/sleha/de-de/xml/article_installation.xml, l10n/sleha/es-es/xml/article_geo_clustering.xml, l10n/sleha/es-es/xml/article_installation.xml, l10n/sleha/fr-fr/xml/article_geo_clustering.xml, l10n/sleha/fr-fr/xml/article_installation.xml, l10n/sleha/it-it/xml/article_geo_clustering.xml, l10n/sleha/it-it/xml/article_installation.xml, l10n/sleha/ja-jp/xml/article_geo_clustering.xml, l10n/sleha/ja-jp/xml/article_installation.xml, l10n/sleha/ja-jp/xml/book_administration.xml, l10n/sleha/pt-br/xml/article_geo_clustering.xml, l10n/sleha/pt-br/xml/article_installation.xml, l10n/sleha/zh-cn/xml/article_geo_clustering.xml, l10n/sleha/zh-cn/xml/article_installation.xml, l10n/sleha/zh-cn/xml/article_nfs_storage.xml, l10n/sleha/zh-cn/xml/article_pacemaker_remote.xml, l10n/sleha/zh-cn/xml/book_administration.xml, l10n/sleha/zh-cn/xml/book_geo_clustering.xml, l10n/sleha/zh-tw/xml/article_geo_clustering.xml, l10n/sleha/zh-tw/xml/article_installation.xml, l10n/sleha/zh-tw/xml/book_administration.xml
1.  Add its namespace to root element
2.  Add localized metadata
- SLE-HA 15
=> Add localized metadata for SLE HA 15 SP3

l10n/de-de/xml/art_sle_ha_geo_quick.xml, l10n/de-de/xml/art_sle_ha_install_quick.xml, l10n/es-es/xml/art_sle_ha_geo_quick.xml, l10n/es-es/xml/art_sle_ha_install_quick.xml, l10n/fr-fr/xml/art_sle_ha_geo_quick.xml, l10n/fr-fr/xml/art_sle_ha_install_quick.xml, l10n/it-it/xml/art_sle_ha_geo_quick.xml, l10n/it-it/xml/art_sle_ha_install_quick.xml, l10n/ja-jp/xml/art_sle_ha_geo_quick.xml, l10n/ja-jp/xml/art_sle_ha_install_quick.xml, l10n/ja-jp/xml/book_sle_ha_guide.xml, l10n/pt-br/xml/art_sle_ha_geo_quick.xml, l10n/pt-br/xml/art_sle_ha_install_quick.xml, l10n/zh-cn/xml/art_sle_ha_geo_quick.xml, l10n/zh-cn/xml/art_sle_ha_install_quick.xml, l10n/zh-cn/xml/art_sle_ha_nfs_quick.xml, l10n/zh-cn/xml/art_sle_ha_pmremote.xml, l10n/zh-cn/xml/book_sle_ha_geo.xml, l10n/zh-cn/xml/book_sle_ha_guide.xml, l10n/zh-tw/xml/art_sle_ha_geo_quick.xml, l10n/zh-tw/xml/art_sle_ha_install_quick.xml, l10n/zh-tw/xml/book_sle_ha_guide.xml
1.  Add its namespace to root element
2.  Add localized metadata
- SLE-HA 15
=> Add localized metadata for SLE HA 15 SP2

de/xml/art_sle_ha_geo_quick.xml, de/xml/art_sle_ha_install_quick.xml, es/xml/art_sle_ha_geo_quick.xml, es/xml/art_sle_ha_install_quick.xml, fr/xml/art_sle_ha_geo_quick.xml, fr/xml/art_sle_ha_install_quick.xml, it/xml/art_sle_ha_geo_quick.xml, it/xml/art_sle_ha_install_quick.xml, ja/xml/art_sle_ha_geo_quick.xml, ja/xml/art_sle_ha_install_quick.xml, ja/xml/book_sle_haguide.xml, pt_br/xml/art_sle_ha_geo_quick.xml, pt_br/xml/art_sle_ha_install_quick.xml, zh_cn/xml/art_sle_ha_geo_quick.xml, zh_cn/xml/art_sle_ha_install_quick.xml, zh_cn/xml/book_sle_haguide.xml, zh_tw/xml/art_sle_ha_geo_quick.xml, zh_tw/xml/art_sle_ha_install_quick.xml, zh_tw/xml/book_sle_haguide.xml
1.  Add its namespace to root element
2.  Add localized metadata
- SLE-HA 15
=> Add localized metadata for SLE HA 12 SP5

xml/ha_netbonding.xml
I couldn't find the file originally listed here, even after installing `kernel-source`, so I've changed it to a link to the same doc online. We use this same link in https://documentation.suse.com/smart/network/html/network-bond-managing-devices/index.html#network-bond-modes. 
* bsc#1231633
* jsc#DOCTEAM-1618
- SLE-HA 15
- SLE-HA 12
=> Update bonding HOWTO link

xml/article_installation.xml
The next steps section needed a bit about adding more STONITH devices.
- SLE-HA 15
- SLE-HA 12
=> Add STONITH to instquick Next Steps

xml/article_geo_clustering.xml, xml/article_installation.xml, xml/article_nfs_storage.xml, xml/article_pacemaker_remote.xml, xml/book_administration.xml, xml/book_geo_clustering.xml
Set date in revision history to FCS date for 15 SP7 and keep initial entry as agreed with @lvicoun.
- SLE-HA 15
=> Revision History: initial entry for FCS of 15 SP7 

xml/ha_gfs2.xml, xml/ha_glossary.xml
Added some more terms to the glossary.
* jsc#DOCTEAM-1766
- SLE-HA 15
- SLE-HA 12
=> Add more terms to glossary

xml/article_geo_clustering.xml, xml/article_installation.xml, xml/geo_booth_i.xml, xml/geo_concept_i.xml, xml/geo_manage_hawk2_i.xml, xml/geo_sync_i.xml, xml/ha_acl.xml, xml/ha_cluster_lvm.xml, xml/ha_concepts.xml, xml/ha_config_basics.xml, xml/ha_config_hawk2.xml, xml/ha_configuring_resources.xml, xml/ha_drbd.xml, xml/ha_glossary.xml, xml/ha_hawk2_batch_i.xml, xml/ha_hawk2_history_i.xml, xml/ha_hawk2_monitor_i.xml, xml/ha_lb_lvs.xml, xml/ha_management.xml, xml/ha_managing_resources.xml, xml/ha_migration.xml, xml/ha_naming.xml, xml/ha_ocfs2.xml, xml/ha_qdevice-qnetd.xml, xml/ha_rear.xml, xml/ha_resource_constraints.xml, xml/ha_samba.xml, xml/ha_storage_protection.xml, xml/ha_troubleshooting.xml, xml/ha_yast_cluster.xml
Spelling, style and link checks. The improved Vale pointed out lots of missing image text, so I added it. It pointed out a lot of other style suggestions too, but for this release I tried not to change too many existing (i.e. already translated) sentences.
- SLE-HA 15
- SLE-HA 12
=> SP7 quality checks

xml/ha_config_basics.xml
Moved a small para to a more appropriate place.
* bsc#1245589
* jsc#DOCTEAM-1895
- SLE-HA 15
- SLE-HA 12
=> Move expected votes example to correct callout
