xml/ha_config_cli.xml

Technically, this would also work:
crm resource meta ipaddress set maintenance true
But I thought using the maintenance command is a bit cleaner.

Fix typo in per-resource maintenance mode command

---

xml/art_sle_ha_install_quick.xml

- cleaning up: remove some commented snippets
- add missing <literal> tags for alice and bob
- replace some references to SLES Guides with direct URLs
- mention cluster scripts in titles of procedures
- modify section title for second node section
- pro.ha.inst.quick.setup.ha-cluster-init: rephrase some steps
- move important note about password to (hopefully) better place
- remove section about configuring a stonith device
(already configured with SBD during ha-cluster-init)

some modifications for Quick Start

---

xml/ha_drbd.xml

Fix few issues in chapter "17.3.3 Initializing and Formatting DRBD Resource"
Replace obsolete "syncer" section to "disk" section.
Add volume id of resource to step3.
Step6~7 should followed with step2, either run step3~5 or step 6~7.
Status in step5 should be Primary/Secondary UpToDate/UpToDate.
Remove the volume id in step8.

fix bsc#990412 and bsc#9906115

---

xml/ha_clvm.xml
xml/ha_config_cli.xml
xml/ha_config_example.xml

The resource agent for clvm from lvm2 package is
kind of deprecated now. Prefer to use ocf:heartbeat:clvm
from upstream instead.
bsc#1030841
update for SLE-HA-12-SP2 at least, recommended for all SLE12
branches, if possible.
Signed-off-by: Eric Ren <zren@suse.com>

clvm: we prefer to use ocf:heartbeat:clvm now

---

xml/art_sle_ha_geo_quick.xml

Just a small thing,but the geo-join command had an extra trailing slash at the end. :)

Geo Quick: Remove extra trailing slash

---

xml/ha_cluster_md.xml

Since raid10 is supported as technical preview,
modify the doc accordingly.
Signed-off-by: Guoqing Jiang <gqjiang@suse.com>

ha_cluster_md: add the description for raid10

---

xml/art_sle_ha_install_quick.xml
xml/book_sle_ha_guide.xml
xml/ha_cluster_lvm.xml
xml/ha_concepts.xml
xml/ha_config_basics.xml
xml/ha_config_example.xml
xml/ha_gfs2.xml
xml/ha_glossary.xml
xml/ha_intro.xml
xml/ha_ocfs2.xml
xml/ha_storage_protection.xml
xml/nfs_quick_clusterscript.xml

With FATE#323203 - "Enable lvmlockd", we will use lvmlockd
to replace the old "clvmd" daemon. People get used to see
"clvm" acronym the same as "clvmd". So, we'd better remove
all "clvm" acronym. Like cluster MD, we tend to use cluster
LVM instead.
Well, manay clvm/cLVM still exist. Anyway, I will remove the
cmirror setction and some configuration steps in the consequent
commits.
Signed-off-by: Eric Ren <zren@suse.com>

cluster lvm: avoid the usage of clvm term

---

xml/ha_lb_lvs.xml

- kernel modules formerly packaged in cluster-network-kmp
are now part of kernel-default package (Fate#323221)
- any other content changes required?

fix bsc#1067156: adjust package name

---

xml/ha_acl.xml
xml/ha_config_basics.xml
xml/ha_fencing.xml
xml/ha_hawk2_cons_i.xml
xml/ha_hawk2_manage_i.xml
xml/ha_hawk2_rsc_i.xml
xml/ha_hawk_rsc_config_i.xml
xml/ha_hawk_rsc_manage_i.xml
xml/ha_troubleshooting.xml

- run daps checklink for all documents
- update most links to clusterlabs.org:
http://www.clusterlabs.org/doc/ changed to
http://www.clusterlabs.org/pacemaker/doc/
- remove outdated link to http://www.linux-ha.org/
(the page itself point to clusterlabs.org),
keeping links to some of its subpages though because they are
still ok)

check and update external links

---

xml/ha_storage_protection.xml

* A new section "Configuring Diskless SBD" according to FATE#321017
* A new section "Testing SBD and Fencing" which describes some general methods to test SBD and fencing (regardless if there is a disk or not)
@taroth21 It seems, the section about diskless SBD is quite short, so it doesn't make sense to split the procedure into several (sub) procedures (as you did in the section "Setting Up SBD with 1-3 Devices". I hope this is ok.
Many thanks! :+1: :+1: :heartbeat:

Fix FATE#321017: Include diskless mode into SBD

---

xml/ha_storage_protection.xml

* Distinguish between predictable and random delays
* Describe `pcmk_delay_base` and `pcmk_delay_max` to fix FATE#324488
@gao-yan: Could you have a look if that makes sense? Especially if you have a tip how to set the `pcmk_delay_base` on a specific node would be highly appreciated. :wink:
Thanks!

Implement FATE#324488

---

xml/ha_samba.xml

- use correct prefixes for groups, clones, colocations and order constraints (see also `ha_naming.xml`)
- rename base-clone to cl-storage (DLM resource)  to comply with naming conventions and upcoming changes from PR#82 (which is not merged yet because of bsc#1089339#c15)

apply naming conventions to CTBD chapter

---

xml/art_sle_ha_pmremote.xml
xml/geo_resources_i.xml
xml/ha_maintenance.xml
xml/ha_migration.xml
xml/ha_storage_protection.xml
xml/ha_troubleshooting.xml
xml/ha_yast_cluster.xml
xml/phrases-decl.ent

In SLE-15-SP1 we recommend users to use the crm shell to start/stop/restart the cluster or query its status, instead of using systemctl.

systemctl start/stop/status pacemaker --> crm cluster start/stop/restart/status

---

DC-SLE-HA-pmremote-quick

* `DC-SLE-HA-all` has the MAIN value set to `MAIN.SLEHA.xml` where we find  `book_sle_ha_techguides.xml` which includes `art_sle_ha_pmremote.xml`, which means that we build it with the whole set.
* `DC-SLE-HA-pmremote-quick` has the MAIN value set to `art_sle_ha_pmremote.xml`, which normally means that we want to build it separately. That's not the case.
* 12 SP4
* 12 SP3
* 12 SP2

Change pmremote MAIN to MAIN.SLEHA.xml

---

README.adoc

We have changed to a new branching model in this repository. We have switched the default branch from `develop` to `master` and have deleted `develop` on the server. 
@aginies @aleksei-burlakov @ChrisKowalczyk @cjschroder @froh @fsundermeyer @GuoqingJiang @keichwa @krig @liangxin1300 @ls-zhu @mschnitzer @renzhengeek
@sknorr @svenseeberg @tomschr @Werkov @zzhou1
This is just for your information. If you want to continue contributing to this repository, please see the latest version of the README for instructions on how to update your local repository after the switch.

README: switch 'develop' -> 'master'

---

xml/MAIN.SLEHA.xml
xml/art_sle_ha_geo_quick.xml
xml/art_sle_ha_install_quick.xml
xml/art_sle_ha_nfs_quick.xml
xml/art_sle_ha_pmremote.xml
xml/book_sle_ha_geo.xml
xml/geo_challenges_i.xml
xml/geo_concept_i.xml
xml/geo_docupdates.xml
xml/geo_drbd_i.xml
xml/geo_ip_i.xml
xml/geo_manage_i.xml
xml/geo_requirements_i.xml
xml/geo_resources_i.xml
xml/geo_sync_i.xml
xml/geo_trouble_i.xml
xml/geo_upgrade_i.xml

Remove  ```<dm:docmanager>``` and ```<inof/>``` elements where not needed: Bugtracking info is inherited from the MAIN file. As all deliverables have moved into the same set meanwhile, removed bugtracking info from individual deliverables - this avoids having to adjust the bugtracking info multiple times. Also corrected bugtracking info in MAIN (word 'Extension' was missing in Bugzilla string).  In addition, some files (especially *Geo Guide*) contained (wrong) info about translation for historical reasons, removed this info to avoid confusion.  

Clean up <info/> elements

---

xml/ha_storage_protection.xml

* Rename driver for Fujitsu systems: `iTCO_wdt` -> `ipmi_watchdog`; add separate row
* Rephrase short sentence about whom to ask (hardware and system vendors)
(Bug was filed against SLEHA15SP1; it's likely this needs backports for other releases too)

Fix bsc#1150990 Rename Fujitsu watchdog driver

---

xml/art_sle_ha_geo_quick.xml
xml/art_sle_ha_install_quick.xml
xml/art_sle_ha_pmremote.xml
xml/book_sle_ha_geo.xml
xml/common_intro_available_doc_i.xml
xml/entity-decl.ent
xml/geo_booth_i.xml
xml/geo_docupdates.xml
xml/geo_ip_i.xml
xml/geo_more_i.xml
xml/geo_overview_i.xml
xml/geo_resources_i.xml
xml/ha_acl.xml
xml/ha_cluster_lvm.xml
xml/ha_install.xml
xml/ha_migration.xml
xml/ha_rear.xml
xml/phrases-decl.ent

Updating the links to our doc pages from www.suse.com/documentation to www.documentation.suse.com.
For QA, I checked the HTML build for SLE-HA-all, no www.suse.com/documentation occurrences found. Also ran ```daps checklink```. no broken links to documentation.suse.com reported.

Update Doc URLs

---

xml/art_sle_ha_pmremote.xml
xml/ha_migration.xml
xml/ha_requirements.xml

From  bsc#115038:
"The inconsistent terminology for the upgrade scenarios between the base product (SLE) and SLE HA is also a point of confusion, both internally and for our customers."
Implementing a proposal by Yan for the SLE HA docs:
- Rolling Upgrade -> Cluster Rolling Upgrade
- Offline Migration -> Cluster Offline Upgrade

Adjust Terminology for Upgrading the Cluster (bsc#1150382)

---

xml/art_sle_ha_geo_quick.xml
xml/art_sle_ha_install_quick.xml
xml/art_sle_ha_pmremote.xml
xml/book_sle_ha_geo.xml
xml/common_intro_available_doc_i.xml
xml/entity-decl.ent
xml/geo_booth_i.xml
xml/geo_docupdates.xml
xml/geo_ip_i.xml
xml/geo_more_i.xml
xml/geo_overview_i.xml
xml/geo_resources_i.xml
xml/ha_acl.xml
xml/ha_cluster_lvm.xml
xml/ha_install.xml
xml/ha_migration.xml
xml/ha_rear.xml
xml/phrases-decl.ent

Updated URLs to documentation.suse.com (#125)
- based on the following guidelines:
*  avoid entities for URLs (entities for parts of the URL make it harder to
copy/paste/replace complete URLs, plus they will be resolved during
translation anyway)
-> this way the URLs are the same in the English versions and translation
branches and can replaced the same way if needed
*  using upcoming 15-SP2 URLs 
(they will only work after FCS, but it prevents us from updating them
in the translation branches after FCS)
* use links to html instead of single-html (shorter download times, SEO)
* use descriptive text for links to mention book name
(in case deeplink is broken, plus better accessibility)

update links to documentation.suse.com

---

xml/art_sle_ha_geo_quick.xml
xml/art_sle_ha_install_quick.xml
xml/art_sle_ha_pmremote.xml
xml/book_sle_ha_geo.xml
xml/common_intro_available_doc_i.xml
xml/entity-decl.ent
xml/geo_booth_i.xml
xml/geo_docupdates.xml
xml/geo_ip_i.xml
xml/geo_more_i.xml
xml/geo_overview_i.xml
xml/geo_resources_i.xml
xml/ha_acl.xml
xml/ha_cluster_lvm.xml
xml/ha_install.xml
xml/ha_migration.xml
xml/ha_rear.xml
xml/phrases-decl.ent

Updating URLs to documentation.suse.com (#125)
Based on the following guidelines:
- avoid entities for URLs (entities for parts of the URL make it harder to
copy/paste/replace complete URLs, plus they will be resolved during
translation anyway)
-> this way the URLs are the same in the English versions and translation
branches and can replaced the same way if needed
- using 15-GA URLs
- use links to html instead of single-html (shorter download times, SEO)
- use descriptive text for links to mention book name
(in case deeplink is broken, plus better accessibility)

Update Doc URLs for SLE HA 15

---

xml/ha_requirements.xml

We should just delete the following line in SLE12SP4+ and SLE15 code
stream. It is outdated back in SLE11 and contradictory nowadays against
Cluster MD feature in the product.
"Hardware-based RAID is recommended. Host-based software RAID is not
supported for all configurations."
bsc#1152414 for discussion as well,  if any.

contradictory RAID description against Cluster MD

---

xml/ha_troubleshooting.xml

Hawk needs to be restarted with "systemctl restart hawk" to reload the new certificate.
See [bsc#1158207](https://bugzilla.suse.com/show_bug.cgi?id=1158207) for details.
@gao-yan: could you have a quick look? I guess this would apply to SLEHA12 SP4/SP5 as well, right?

Fix bsc#1158207 add missing service into new step

---

xml/ha_maintenance.xml
xml/ha_yast_cluster.xml

This PR fixes bsc#1155609 and contains the following changes:
* In `ha_maintenance.xml`:
- Explain the recommended way (crm cluster start|stop|restart|status)
- Refer to SUSE blog for details
* In ha_yast_cluster.xml`:
- Amend title ("... at the Node Level")
- Use "cluster service" instead of mentioning Pacemaker (recommended by Yan)
- Update output of "crm status"
We are on hold to backport this to SLE15SP0/SP1 untill further feedback from customers.
----
@zzhou1 This is a first draft of the above Bugzilla entry. Would you like to review it? I can also create a PDF in case you need it.

Fix bsc#1155609 Explain System Level Concept

---

xml/ha_migration.xml

Fix for https://bugzilla.suse.com/show_bug.cgi?id=1158534:  [doc] 5.2.1 Supported Upgrade Paths for SLE HA and SLE HA Geo - skip a service pack - supported? 

Bugfix: Skipping Service Packs (bsc#1158534)

---

xml/art_sle_ha_install_quick.xml
xml/book_sle_ha_guide.xml
xml/entity-decl.ent
xml/ha_qdevice-qnetd.xml
xml/ha_storage_protection.xml

This is a draft for QDevice/QNetd and ECO jira#1745.
See also https://bugzilla.suse.com/show_bug.cgi?id=1171385
It's a new chapter in the Administration Guide. In the Quick Start, there is only a small list item that mentions it and for more information, it refers to this new chapter.
----
PDF file: 
[cha-ha-qdevice_remarks_color_draft_en-6f212969.pdf](https://github.com/SUSE/doc-sleha/files/4633103/cha-ha-qdevice_remarks_color_draft_en-6f212969.pdf)

Fix jira#1745 (ECO) Add QDevice/QNetd

---

xml/ha_cluster_lvm.xml

In SLE15, we don't use Cluster VG anymore, but instead of Shared VG.
The `vgdisplay` doesn't print this information, but it can be retrieved by the `vgs` command.
bsc#1173007

Fix bsc#1173007: Clarify vgdisplay

---

xml/ha_migration.xml

Extend important note to clarify what happens when nodes with older versions try to (re)join
See [bsc#1174245](https://bugzilla.suse.com/show_bug.cgi?id=1174245)

Fix bsc#1174245: Rejoin after cluster rolling upgrade

---

xml/ha_qdevice-qnetd.xml

Related to bsc#1174929, reported by Dario.

Fix bsc#1174929: Mention NR for corosync-quorumtool

---

xml/ha_acl.xml

This PR fixes bsc#1176035 and contains:
* Move section ID=sec-ha-acl-enable after Conceptual Overview
* Rename titles:
- ID=`sec-ha-acl-basics`:
The Basics of ACLs -> Conceptual Overview
- ID=`sec-ha-acl-config-hawk2`:
Configuring ACLs with &hawk2; -> Creating a Read-Only Monitor Role with &hawk2;
- ID=`sec-ha-acl-config-crm`:
Configuring ACLs with &crmsh; -> Creating a Read-Only Monitor Role with &crmsh;
* Move sect2 (ID=`sec-ha-acl-config-xpath`) to the end and create a sect1
* Move sect2 (ID=`sec-ha-acl-config-tag`) to the end and create a sect1
* Add two new sections:
- `sec-ha-acl-rm-user`: Removing a User
- `sec-ha-acl-rm-role`: Removing an Existing Role

Rework ACL chapter (bsc#1176035)

---

xml/ha_storage_protection.xml

Configuring an sg_persist Resource" step "6. Check all your changes with the show command."
"show" should be "show changed";  otherwise you'll see the whole configuration.

Fix #1179220: Command "show" -> "show changed"

---

xml/ha_storage_protection.xml

It seems, watchdog drivers can also be found in a different directory `/lib/modules/<version>/kernel/drivers/char/ipmi/`).
=> Add dir into the floating text
Add verifying step.
See bsc#1179194

Fix #1179194: Add missing path & verify step

---

xml/ha_storage_protection.xml

Addition for bsc#1179194
Clarifiy conflicting kernel modules.

Clarify conflicting kernel modules

---

xml/ha_yast_cluster.xml

In section "Synchronizing Connection Status Between Cluster Nodes" (ID=sec-ha-installation-setup-conntrackd) we have two procedures. However, that doesn't work much as it just confuses readers. 
To clarify that, we should merge these two procedures into one.
Related to bsc#1179006

Merge two procedures into one

---

xml/ha_yast_cluster.xml

Mention when the parameter `bindnetaddr` is not strictly required.
@gao-yan
I've added your small sentence into the "Bind network address" at http://docserv.suse.de/documents/SLE-HA_15_SP3/SLE-HA-guide/html/cha-ha-ycluster.html#sec-ha-installation-terms
I've considered other location, but haven't found a better one.
Would that be appropriate location?

Fix bsc#1121875: when bindnetaddr is not required

---

xml/ha_storage_protection.xml

* Use `-w` option instead of `-d`
* Fix typo in replaceable, should be `WATCHDOG_DEVICE` instead of `WATCHDOC_DEVICE`

Fix bsc#1184502: use -w for watchdog device

---

xml/ha_qdevice-qnetd.xml

Clients need to install the `corosync-qdevice` package first.
Jira: DOCTEAM-63
Bugzilla: bsc#1183954

Install missing corosync-qdevice

---

xml/ha_ocfs2.xml

https://bugzilla.suse.com/show_bug.cgi?id=1178336, remove acl mount option
No backports, 15 SP3 only.

delete ocfs2 acl mount option

---

xml/ha_config_cli.xml

Deprecate "pingd" resource agent in favor of "ping"
@gao-yan Yan, this is a naive implementation (just replaced `pingd` -> `ping`). Probably this isn't enough. The glossary item is disabled and won't be shown in the output.
Would you mind to have a quick look? :slightly_smiling_face:

Fix bsc#1183651: Replace pingd RA -> ping

---

xml/ha_requirements.xml

Mention the 32 cluster node limit. Add a reference to pacemaker_remote service to avoid this limit.
Fixes DOCTEAM-27 / bsc#1183355

Add 32 cluster node limit

---

xml/ha_storage_protection.xml

With 12 SP4/5 and 15 SP1/2 we got a great improvement "priority fencing". It goes beyond "static fencing delay"
The priority fencing delay is applied in case:
* A node is lost and should be fenced
* The node has the highest node priority
* We don’t have the majority of the nodes in our cluster partition
Fixes DOCTEAM-81 / bsc#1180922
It will appear in [Procedure 11.7: _Configuring the cluster to use SBD_](https://susedoc.github.io/doc-sleha/main/single-html/SLE-HA-guide/#pro-ha-storage-protect-fencing)
---

Describe priority fencing delays

---

xml/ha_storage_protection.xml

In the light of #168, some other related sentences needs to be adapted as well.

Adapt sentences for FATE-324488

---

xml/article_nfs_storage.xml
xml/ha_config_basics.xml
xml/ha_config_cli.xml
xml/ha_fencing.xml
xml/ha_samba.xml
xml/ha_storage_protection.xml
xml/nfs_quick_clusterscript.xml

Internally, "Mandatory" is only used by order constraints. To be consistent with other (upstream) documentation,
use "inf" for location and colocation constraints.
* [bsc#1158626](https://bugzilla.suse.com/show_bug.cgi?id=1158626)
* [DOCTEAM-207](https://jira.suse.com/browse/DOCTEAM-207)
Originates from https://github.com/SUSE/doc-sleha/commit/b71f4c584271fe80c8fc1eed57ddabe7ac60a41d#commitcomment-52178525
----
@gao-yan This is from your comment. I tried to make it consistent with upstream documentation. If possible, could you have a quick look? Many thanks!

Fix DOCTEAM-207: Use Mandatoryi/inf consistently

---

xml/art_sle_ha_nfs_quick.xml

By default, the locking_type set in lvm.conf on SLES 12 SP1 is "1" or file  locking.  SLES 11 SP4 shows "3" as the default; cluster-aware locking.
Add this detail as a first step in "Creating an LVM Device" of the NFS Quick Start Guide.
---
From Garret in [bsc#995663](https://bugzilla.suse.com/show_bug.cgi?id=995663#c2):
> Looks like locking_type was removed from LVM2 in September 2019, I'm thinking this was a major change added right before SP2 was released.
> 
> e.g. The RPM changelog on SLES15 SP2 shows that clvm support was dropped.
>
> sles15sp2:~ # rpm -q --changelog lvm2
> [...]
> * Mon Sep 02 2019 heming.zhao
>    - Update to LVM2.2.03.05
>    - To drop lvm2-clvm and lvm2-cmirrord rpms (jsc#PM-1324)
> [...]
> I checked the packages on the SCC and found that lvm2-clvm is shipped …

Fix bsc#995663: Mention locking_type for LVM

---

l10n/sleha/de-de/xml/MAIN.SLEHA.xml
l10n/sleha/es-es/xml/MAIN.SLEHA.xml
l10n/sleha/fr-fr/xml/MAIN.SLEHA.xml
l10n/sleha/it-it/xml/MAIN.SLEHA.xml
l10n/sleha/ja-jp/xml/MAIN.SLEHA.xml
l10n/sleha/pt-br/xml/MAIN.SLEHA.xml
l10n/sleha/zh-cn/xml/MAIN.SLEHA.xml
l10n/sleha/zh-tw/xml/MAIN.SLEHA.xml

dm:editurls tag removed for all languages of SLE 15 SP3.
Will be done for each branch version separately therefore no backports needed.

SEO: edit urls removed l10n SLE-HA 15 SP3

---

l10n/de-de/xml/MAIN.SLEHA.xml
l10n/es-es/xml/MAIN.SLEHA.xml
l10n/fr-fr/xml/MAIN.SLEHA.xml
l10n/it-it/xml/MAIN.SLEHA.xml
l10n/ja-jp/xml/MAIN.SLEHA.xml
l10n/pt-br/xml/MAIN.SLEHA.xml
l10n/zh-cn/xml/MAIN.SLEHA.xml
l10n/zh-tw/xml/MAIN.SLEHA.xml

dm:editurls tag removed for all languages of SLE-HA15 SP2.
Will be done for each branch version separately therefore no backports needed

SEO: remove editurls from l10n SLEHA15SP2

---

xml/article_nfs_storage.xml

Remove colon after the `fencing` key in the DRBD configuration

Fix bsc#1193441: remove colon after "fencing"

---

xml/ha_config_cli.xml
xml/ha_example_cli_i.xml
xml/ha_troubleshooting.xml

The command `crm resource migrate` has been marked as deprecated and is replaced by `crm resource move`.
[bsc#1189235](https://bugzilla.suse.com/show_bug.cgi?id=1189235)

Fix bsc#1189235: Use move instead of migrate

---

xml/ha_concepts.xml

Mention that mixed clusters of different processor platforms are not supported.
[bsc#1193176](https://bugzilla.suse.com/show_bug.cgi?id=1193176) - hybrid clusters across HA architecure?

bsc#1193176: mention architectures

---

xml/article_pacemaker_remote.xml
xml/geo_resources_i.xml
xml/ha_config_cli.xml
xml/ha_gfs2.xml
xml/ha_ocfs2.xml
xml/ha_storage_basics.xml
xml/ha_storage_protection.xml

In the crm live shell, 'exit' and 'bye' are still accepted, but the shell gives this hint: "This command is deprecated, please use 'quit'"

crm live shell: exit -> quit (bsc#1195098)

---

xml/article_geo_clustering.xml
xml/ha_concepts.xml
xml/ha_geocluster.xml
xml/ha_migration.xml

For Code 15, we removed any occurences which mentioned Geo Clustering as separate extension. However, there are still some left-overs from Code 12 that at least hint in that direction. Let's remove them completely.
This came up as a sidenote in https://bugzilla.suse.com/show_bug.cgi?id=1192769#c4 but it is the not primary target of the bug report, therefore fixed in a separate PR.

Geo Clustering

---

xml/ha_config_cli.xml

For SLE-22500. All references to hb_report had already been replaced, but I added a reference to the log file for crmsh per Tanja's comment in SLE-21746. Let me know if there's anything I've missed that still needs to be done for this issue.
(Looks like my text editor also deleted some white spaces). 
SLE-22500

Add log file path for crmsh

---

xml/geo_ip_i.xml
xml/ha_concepts.xml
xml/ha_config_basics.xml
xml/ha_drbd.xml
xml/ha_glossary.xml
xml/ha_lb_haproxy.xml
xml/ha_netbonding.xml
xml/phrases-decl.ent

General fixes that can be backported. Language in ha-netbonding.xml is more vague than Tomas' SP4 changes in doc-sle, since the GUI hasn't changed in older versions.
Did not change any IDs, even though at least one could use changing (sec-ha-config-basics-resources-advanced-masters).
jsc#SLE-22017

Fix master and slave references in multiple files

---

xml/ha_ocfs2.xml

Kernel 5.8 supports the "nocluster" mount option to enable a use case, when no full functional cluster stack is needed.
[SLE-22507](https://jira.suse.com/browse/SLE-22507)

Fix SLE-222541: nocluster mount option for OCFS2

---

xml/article_geo_clustering.xml
xml/article_installation.xml
xml/article_nfs_storage.xml
xml/geo_booth_i.xml
xml/geo_more_i.xml
xml/geo_resources_i.xml
xml/geo_scripts_i.xml
xml/ha_config_hawk2.xml
xml/ha_hawk2_health_i.xml
xml/ha_lb_haproxy.xml
xml/ha_storage_protection.xml
xml/ha_yast_cluster.xml
xml/phrases-decl.ent

Part 2 of the work for SLE-23068: deprecate ha-cluster-bootstrap package (including the ones for Geo clustering).
Part 1 was done in https://github.com/SUSE/doc-sleha/commit/c5e7346cc00
No backports required.

ha-cluster-bootstrap: update deprecated commands 

---

xml/article_installation.xml

Switched the default from multicast to unicast. Updated steps based on a couple of quick tests.
jsc#DOCTEAM-496

Change to unicast as default in crm cluster init

---

xml/article_pacemaker_remote.xml
xml/ha_maintenance.xml
xml/ha_migration.xml
xml/ha_yast_cluster.xml

This PR comes in two parts:
1. Added a new section for `crm cluster stop --all`. See xml/ha_maintenance in the diff. There are two new paragraphs. Are these descriptions accurate? Is there more information I should include?
2. Added `--all` to commands that seem like they could use it. See the other files in the diff. Are these changes appropriate, or should I undo any of them? 
@liangxin1300 @zzhou1 can you please review?
jsc#SLE-22498

SLE-22498 cluster graceful shutdown

---

xml/ha_clvm.xml

A `dsc` entity was missing the `&`. I think this will fix rows 4, 5, and 6 in the spreadsheet. 
My text editor also deleted a bunch of blank space; sorry for the noise.

SEO: Fix broken link in CLVM chapter

---

images/src/svg/ha_pmremote-virt-guest-nodes.svg

The "cluster stack" section duplicated the text "physical host" from the "hardware" section. It should actually be Pacemaker and Corosync (see [the previous version](https://documentation.suse.com/sle-ha/12-SP3/html/SLE-HA-all/images/ha_pmremote-virt-guest-nodes.svg) and [the other diagrams in that guide](https://documentation.suse.com/sle-ha/15-SP3/html/SLE-HA-all/article-pacemaker-remote.html#sec-ha-pmremote-concept)).

Fix Cluster Stack in virt guest nodes SVG

---

images/src/svg/ha_cluster_example4.svg

The [iSCSI cluster configuration diagram](https://documentation.suse.com/sle-ha/15-SP3/html/SLE-HA-all/cha-ha-concepts.html#id-1.4.3.3.6.7) says "Fibre Channel switch", which seems to be an error (the Fibre Channel diagram is the one above this). See the [12 SP5 version](https://documentation.suse.com/sle-ha/12-SP5/html/SLE-HA-all/cha-ha-concepts.html#id-1.3.3.3.6.6) for comparison.

Fix iscsi cluster diagram

---

xml/article_installation.xml
xml/ha_qdevice-qnetd.xml

You can configure QDevice using the bootstrap script in interactive mode. I've kept the quickstart minimal for now, but the question needed to at least be mentioned. 
jsc#DOCTEAM-499
bsc#1195100

Add QDevice question to crm cluster init

---

xml/geo_sync_i.xml

CSync2 TCP port should be 30865. See https://github.com/LINBIT/csync2/blob/master/doc/csync2.adoc. 
bsc#1186022
DOCTEAM-587

Fix csync2 TCP port

---

xml/ha_storage_protection.xml

Added a warning about blocking cluster communication in the local firewall, especially for diskless SBD.
DOCTEAM-659
BSC#1200331

Add firewall warning for diskless SDB

---

xml/ha_acl.xml
xml/ha_config_basics.xml
xml/ha_gfs2.xml
xml/ha_ocfs2.xml
xml/ha_requirements.xml
xml/ha_storage_protection.xml

I converted some tables into lists, where it made sense to do so. I did a little bit of editing in a couple of them, but mostly tried to avoid changing the content at all. 
Conveniently, all of the tables I could find that needed converting were in the Administration Guide. Here's a PDF of the new version:
[book-administration_color_en.pdf](https://github.com/SUSE/doc-sleha/files/9069283/book-administration_color_en.pdf)
Here's a list of the tables I converted: 
Old: https://documentation.suse.com/sle-ha/15-SP4/html/SLE-HA-all/cha-ha-requirements.html#id-1.4.3.4.4.5 System roles and installed patterns
New: See 2.2 Software requirements in the PDF
Old: https://documentation.suse.com/sle-ha/15-SP4/html/SLE-HA-all/cha-ha-config-basics.html#tab-ha-basics-meta Options for a primitive resource …

Convert two-column tables to lists

---

xml/book_geo_clustering.xml
xml/book_quickstarts.xml

@jfaltenbacher I've added the translation marker to book_quickstarts.xml. I noticed that it also wasn't in book_geo_clustering.xml so I added it there too, but let me know if that isn't necessary.

Add dm:translation

---

xml/ha_storage_basics.xml

Added the port number for DLM. Part 1 of this bug.
jsc#DOCTEAM-82
bsc#1179267

Add DLM port number

---

xml/ha_storage_protection.xml

I added a warning about the chance for a double reset in a split-brain scenario when using pcmk_delay_max.
jsc#DOCTEAM-542
bsc#1196045

Add warning about chance of double reset

---

xml/ha_maintenance.xml

Clarified the action you can take on cluster resources when the cluster or node is in maintenance mode.
DOCTEAM-682
bsc#1200858

Clarify resource actions while in maintenance mode

---

xml/article_nfs_storage.xml
xml/ha_drbd.xml

Changed `/usr/lib/drbd/crm-fence-peer.9.sh` and `/usr/lib/drbd/crm-unfence-peer.9.sh` to `/lib/drbd/crm-fence-peer.9.sh` and `/lib/drbd/crm-unfence-peer.9.sh`. Only found four instances total in the html-single "all" build. 
Checked in test VMs and only found this change in 15 SP4, not 15 SP3 (and presumably earlier), so currently no need for further backporting.
jsc#DOCTEAM-696
bsc#1201901

Change /usr/lib/drbd/ to /lib/drbd/ for fence script

---

xml/article_nfs_storage.xml

Added a callout explaining the purpose of the `fencing` line.
jsc#DOCTEAM-439
bsc#1193441

Add explanation for fencing policy line

---

xml/ha_cluster_md.xml
xml/ha_gfs2.xml
xml/ha_ocfs2.xml
xml/ha_storage_basics.xml

I added procedures for adding separate colocation and order constraints for resources on top of DLM, as opposed to putting them all in one group. This is based on Roger's suggestions from bsc#1179267. I didn't follow it exactly, and made changes in a few places, so I'll add details in a further comment.
(And as usual, my text editor stripped out some wayward blank space).
jsc#DOCTEAM-82
bsc#1179267

Add procedure for configuring multiple DLM resources

---

xml/article_nfs_storage.xml
xml/product-entities.ent

Simplified the NFS virtual IP address on the assumption that network admins will know the options for their setup and can adjust accordingly.
Since I did this by updating an entity, here's the full result: 
[article-nfs-storage_color_en.pdf](https://github.com/SUSE/doc-sleha/files/9422174/article-nfs-storage_color_en.pdf)
jsc#DOCTEAM-145
bsc#1158160

Simplify NFS virtual IP addresses

---

xml/ha_storage_protection.xml

Added a note that the SBD STONITH resource doesn't need to be cloned. A primitive is sufficient.
jsc#DOCTEAM-350
bsc#1186690

Add note: SBD resource does not need to be a clone

---

xml/ha_drbd.xml

Removed the drbdadm bash completion step as it isn't required in SLE15. 
jsc#jiranotworkingrip
bsc#1203483

Remove outdated drbdadm bash completion step

---

xml/article_installation.xml
xml/phrases-decl.ent

Restructured the quickstart a bit, mostly based on the suggestions in DOCTEAM-94, with a couple of extras while I was at it: 
1. Moved the SBD requirements to the system requirements chapter.
2. Removed some extra info from the STONITH requirements section and the SBD section. It didn't match the minimalism of the rest of the guide.
3. Restructured the intro to the Testing chapter, to clearly show the options.
4. Updated commands to have the whole command inside the command tags, per style guide. Eventually I'll do this for all the HA guides.
5. Generally applied some more minimalism.
Here's a PDF: 
[article-installation_color_en.pdf](https://github.com/SUSE/doc-sleha/files/9595933/article-installation_color_en.pdf)
@taroth21 are you happy with these changes? Anything more/less you'd like …

Structural changes for installation quickstart

---

xml/article_pacemaker_remote.xml
xml/ha_config_basics.xml

Added a tip about live migration to the pacemaker remote guide.
Also made small edits to the description of `allow-migrate` in the admin guide. Only the main branch says "live migration"; that was a recent change that I need to backport along with this PR.
jsc#DOCTEAM-588
bsc#1178970

Add tip for enabling live migration of VirtualDomain

---

xml/book_administration.xml

I've moved the maintenance and update/upgrade chapters to a new part. This is quite simple to backport as it only involves moving the includes.
PDF: [book-administration_color_en.pdf](https://github.com/SUSE/doc-sleha/files/9712656/book-administration_color_en.pdf)
I'd also like to restructure the upgrade chapter a bit, but currently I think that's better left for Smart Docs.
jsc#DOCTEAM-112

Move maintenance and upgrade chapters to new part

---

xml/ha_yast_cluster.xml

Moved Csync2 to the end of the YaST section and made it extra clear that you have to click Finish before proceeding.
Also removed the "requirements" list as it was just a summary of what you're about to do in Procedure 4.7, but was presented in a way that made it look like you have to do them _before_ Procedure 4.7.
jsc#DOCTEAM-578
bsc#1178974

Clarify csync2 procedure

---

xml/ha_crmreport_passl.xml

Added a step to pass a user's local SSH keys to the node for `crm report` in https://documentation.suse.com/sle-ha/15-SP3/html/SLE-HA-all/app-crmreport-nonroot.html#sec-crmreport-nonroot-sudo
Looks like my editor also removed some trailing whitespace.
jsc#DOCTEAM-667
bsc#1200367

Add step for passing SSH_AUTH_SOCK via sudo

---

xml/ha_qdevice-qnetd.xml
xml/ha_storage_protection.xml

SBD fails if the watchdog timeout value is less than QDevice's sync timeout value.
I added a note about this to the diskless SBD section:
and the QDevice section: 
(The bootstrap script is fixed, so it should now be set to an appropriate value automatically, but it's still useful to check)
* bsc#1205810
* jsc#DOCTEAM-827
- SLE-HA 15
- SLE-HA 12

Add notes about SBD_WATCHDOG_TIMEOUT with QDevice

---

xml/ha_troubleshooting.xml

Some text had turned green due to a faulty xref (somehow??). This is now fixed. 
* jsc#DOCTEAM-847
- SLE-HA 15
- SLE-HA 12

Fix green text by simplifying xref

---

xml/ha_troubleshooting.xml

`pssh` was removed in SLE-HA 15 and replaced with `crm cluster run`.
* jsc#DOCTEAM-840
* bsc#1205961
- SLE-HA 15
- SLE-HA 12

Remove pssh and add crm cluster run

---

xml/ha_cluster_md.xml

Changed the sdX names in mdadm.conf to stable device names.
* bsc#1199688
* jsc#DOCTEAM-648
- SLE-HA 15
- SLE-HA 12

Recommend stable device names for mdadm

---

xml/ha_crmreport_passl.xml

Added the `hareport` user to the `crm cluster` command, as it fails otherwise. This won't be required in 15 SP5 due to a new feature being worked on right now, and which will also be backported to 15 SP4. 
* bsc#1206167
* jsc#DOCTEAM-854
- SLE-HA 15
- SLE-HA 12

Add -u hareport to crm report

---

xml/article_geo_clustering.xml
xml/article_installation.xml

Updated the installation section of the Geo quickstart to be more like the same section of the regular quickstart, and ended up improving the regular quickstart while I was at it. 
* jsc#DOCTEAM-836
- SLE-HA 15
- SLE-HA 12

Improve quickstart installation sections

---

xml/ha_qdevice-qnetd.xml

`--qdevice-hostname` should be `--qnetd-hostname`.
* bsc#1206498
* jsc#DOCTEAM-867
- SLE-HA 15
- SLE-HA 12

Fix qdevice-hostname -> qnetd-hostname

---

xml/ha_maintenance.xml

I restructured the Maintenance chapter to hopefully be a bit more straightforward. I mostly just moved content to new locations, but I did a little editing as well.
Original chapter: https://documentation.suse.com/sle-ha/15-SP4/html/SLE-HA-all/cha-ha-maintenance.html
New chapter: [cha-ha-maintenance_color_en.pdf](https://github.com/SUSE/doc-sleha/files/10256945/cha-ha-maintenance_color_en.pdf)
* jsc#DOCTEAM-831
- SLE-HA 15
- SLE-HA 12

Restructure maintenance chapter

---

xml/ha_ocfs2.xml

Added the defragfs.ocfs2 tool.  Will also be added to 15 SP4 and 15 SP3 but not until later in the 15 SP5 cycle. 
Engineering ticket is still in progress, but the tool is in the latest snapshot, so I think it's safe to add it now as the doc change is very small and not likely to change based on further testing/QA.  
* jsc#PED-921
- SLE-HA 15
- SLE-HA 12

Add defragfs.ocfs2

---

xml/article_geo_clustering.xml
xml/geo_resources_i.xml
xml/ha_acl.xml
xml/ha_naming.xml
xml/ha_resource_constraints.xml
xml/ha_storage_protection.xml
xml/phrases-decl.ent

Order constraint vs ordering constraint was used haphazardly (and google search results are similarly inconclusive). With no definitive answer on which to use, I went with order constraint because ordering constraint has a small chance for ambiguity. 
* jsc#DOCTEAM-832
- SLE-HA 15
- SLE-HA 12

Terminology: order constraint

---

xml/ha_storage_protection.xml

There was still one instance of `ms` instead of `clone`. I changed it based on how I changed all the previous instances. Also, based on those previous changes, this only goes back as far as 15 SP4.
* bsc#1207389
* jsc#DOCTEAM-883
- SLE-HA 15
- SLE-HA 12

Change deprecated ms to clone

---

xml/book_administration.xml
xml/ha_config_basics.xml
xml/ha_config_cli.xml
xml/ha_config_hawk2.xml
xml/ha_hawk2_batch_i.xml

Final PR for DOCTEAM-106. Consolidates the remaining sections into the Basics chapter. Not too much shuffling required for this one, and I didn't need to create any new files, so I should be able to cherry-pick this one back to SP1. 
* jsc#DOCTEAM-106
- SLE-HA 15
- SLE-HA 12

Consolidate remaining config into basics chapter

---

xml/ha_storage_protection.xml

Per DOCTEAM-834, step 4 was a little confusing as there's a lot of info there and it's not immediately obvious that this is the step where you configure the resource (at least until you scroll past and see that there's nothing else after it). 
I thought the fix would be more complex, but actually all I ended up doing was moving the context from the start of the procedure to the appropriate steps. It's still not an ideal structure for a step in a procedure, but for the purposes of this issue (making clear what the step actually is), this fix does the trick. 
* jsc#DOCTEAM-834
- SLE-HA 15
- SLE-HA 12
When opening a PR, do …

Clarify SBD STONITH resource step

---

xml/article_installation.xml
xml/article_nfs_storage.xml
xml/ha_iscsi_for_sbd.xml

I've addressed two JIRA issues in this PR: 
**DOCTEAM-144**
* Clarified the STONITH item in the NFS quick start guide. This section is a usage scenario rather than a list of requirements, so not an appropriate place to go into a lot of detail.
* Added more detail to the STONITH requirement in the Installation quick start guide.
**DOCTEAM-107**
* Added an appendix with simple procedures to add iSCSI storage for use with SBD. I've tried to clearly mark it as just a simple option for testing purposes, but I think it's really useful to include as an easy way to get SBD for testing out an HA cluster, even if you know nothing about shared storage. 
* bsc#1158162
* jsc#DOCTEAM-144
* jsc#DOCTEAM-107
- SLE-HA 15
- …

Clarify and improve STONITH requirement

---

xml/ha_gfs2.xml

Added a warning that we only support read for GFS2, not write.
* bsc#1209530
* jsc#DOCTEAM-936
- SLE-HA 15
- SLE-HA 12

Clarify GFS2 read-only support

---

xml/geo_concept_i.xml
xml/geo_manage_i.xml
xml/ha_cluster_lvm.xml
xml/ha_configuring_resources.xml
xml/ha_drbd.xml
xml/ha_fencing.xml
xml/ha_glossary.xml
xml/ha_maintenance.xml
xml/ha_storage_protection.xml
xml/ha_troubleshooting.xml

This issue came up in https://github.com/SUSE/doc-sleha/pull/320.
Change the spelling of 'split brain' to 'split-brain' across the complete set of SLE-HA docs. 
See https://github.com/SUSE/doc-sleha/pull/320#issuecomment-1541962795
- SLE-HA 15
- SLE-HA 12

Terminology: 'split brain' to 'split-brain'

---

xml/ha_migration.xml

The Upgrade chapter was lacking entries for the latest SP version. 
- SLE-HA 15
- SLE-HA 12

Upgrade chapter: add entries for SP5

---

xml/article_installation.xml
xml/article_nfs_storage.xml
xml/product-entities.ent

The approach detailed in the NFS guide was potentially harmful, as detailed in https://www.suse.com/support/kb/doc/?id=000020396. 
This new version describes a different approach that hopefully avoids the common pitfalls. 
Here is a PDF for anyone who wants to see a rendered version in addition to the diff: 
[article-nfs-storage_en.pdf](https://github.com/SUSE/doc-sleha/files/11539494/article-nfs-storage_en.pdf) **(updated 2023-05-23)**
* bsc#1201271
* jsc#DOCTEAM-473
- SLE-HA 15
- SLE-HA 12
**Note** that I'll need to change `clone` back to `ms` for versions 12 SP5 and SP4.
When opening a PR, do *not* set the following …

Overhaul HA NFS guide

---

xml/ha_agents.xml
xml/ha_fencing.xml
xml/ha_samba.xml
xml/ha_storage_protection.xml

I checked the links that were commented out for the last loc drop, and mostly didn't find any good replacements, so I've removed most of them for good. I did replace one with a link to clusterlabs. 
It probably makes sense to backport this change, since the old links are presumably broken in the earlier versions, too.
- SLE-HA 15
- SLE-HA 12

Admin Guide linkcheck: replace or remove commented links

---

xml/art_sle_ha_install_quick.xml
xml/art_sle_ha_nfs_quick.xml

Here is the NFS guide overhaul, with changes for 12 SP5.
Changes specifically for 12 SP5 are in separate commits from the changes cherry-picked from 15 SP4/5.
PDF: 
[art-ha-quick-nfs_en.pdf](https://github.com/SUSE/doc-sleha/files/11621486/art-ha-quick-nfs_en.pdf)
* bsc#1201271
* jsc#DOCTEAM-473
- SLE-HA 15
- SLE-HA 12

NFS overhaul (for 12 SP5)

---

xml/art_sle_ha_nfs_quick.xml

Since the new NFS guide can't be backported to all version due to technical changes, here is a warning directing people to newer versions.
PDF: 
[art-sleha-nfs-quick_en.pdf](https://github.com/SUSE/doc-sleha/files/11621886/art-sleha-nfs-quick_en.pdf)
* bsc#1201271
* jsc#DOCTEAM-473
- SLE-HA 15
- SLE-HA 12

Add warning to older NFS guides

---

xml/article_installation.xml
xml/ha_config_cli.xml
xml/ha_crmreport_passl.xml

New feature allowing you to set up the cluster and run cluster tasks as a sudo user instead of root. I'll include details of the changes in a comment.
* jsc#PED-2861
- SLE-HA 15
- SLE-HA 12

crmsh can use non-root sudoer SSH keys

---

xml/ha_concepts.xml

Live migration is supported, but is risky. I've added a warning along with suggestions for lowering the risk.
* bsc#1210426
* jsc#DOCTEAM-969
- SLE-HA 15
- SLE-HA 12

Add warning about live migration in active clusters

---

xml/article_nfs_storage.xml
xml/ha_cluster_lvm.xml
xml/ha_cluster_md.xml
xml/ha_drbd.xml
xml/ha_gfs2.xml
xml/ha_ocfs2.xml
xml/ha_storage_protection.xml

Changes sdX names to stable names (or replaceables), especially in commands where it's very easy to just copy what's there without thinking. 
* bsc#1213522
* jsc#DOCTEAM-1057
- SLE-HA 15
- SLE-HA 12

Change sdX names to stable names where appropriate

---

xml/ha_managing_resources.xml

I ran into the initial issue with procedure (need to stop the resource first) while doing something else. I've since tested it, both typing the full commands and via the crm shell, and found this wasn't the only issue. I have therefore fixed up the whole procedure.
* jsc#DOCTEAM-1113
- SLE-HA 15
- SLE-HA 12

Fix removing resources with crmsh procedure

---

xml/ha_configuring_resources.xml

Added `allow-unhealthy-nodes` to the list of resource meta attributes. 
Also updated the introductory sentence of the list so that it isn't misleading if the list falls out of date.
* bsc#1215886
* jsc#DOCTEAM-1126
- SLE-HA 15
- SLE-HA 12

Add info about allow-unhealthy-nodes attribute

---

xml/geo_booth_i.xml
xml/ha_management.xml
xml/ha_managing_resources.xml
xml/ha_resource_constraints.xml

Made a few improvements to the resource cleanup section: 
* Fixed spelling of "failcount" to "fail count"
* Updated `crm resource list` to `crm resource status`
* Added info about fail counts not being cleaned automatically by default
* Improved the crmsh procedure, esp. by adding a command to actually see the fail count
* bsc#1211019
* jsc#DOCTEAM-977
- SLE-HA 15
- SLE-HA 12

Improve resource cleanup section

---

xml/article_installation.xml
xml/ha_cluster_lvm.xml
xml/ha_concepts.xml
xml/ha_config_example.xml
xml/ha_glossary.xml
xml/ha_migration.xml
xml/ha_storage_protection.xml
xml/nfs_quick_clusterscript.xml

* Used the existing `clvm` entity in the remaining places where it wasn't used.
* Changed all instances of LVM2 (except package names and command output) to LVM. As far as I can tell, LVM1 is obsolete, so I think it's safe to just use the term LVM without causing confusion.
* jsc#DOCTEAM-111
- SLE-HA 15
- SLE-HA 12

Terminology: LVM, LVM2, and Cluster LVM

---

xml/ha_drbd.xml

The DRBD chapter was lacking a procedure for adding a cluster resource to manage the DRBD device. However, the HA NFS guide does have this procedure, so I've reproduced it in the DRBD chapter with some minor edits to make it fit the context.
The chapter overall could use improvements to its flow, but that's for another PR.
* bsc#1211587
* jsc#DOCTEAM-998
- SLE-HA 15
- SLE-HA 12

Add procedure for creating a DRBD cluster resource

---

xml/article_geo_clustering.xml
xml/article_installation.xml
xml/ha_config_basics.xml
xml/ha_glossary.xml
xml/ha_loadbalancing.xml

Added items for "site" and "location" in the glossary. I didn't include the non-constraint meaning of location, even though it's used in a few places, because it's just a regular non-technical word.
* jsc#DOCTEAM-108
- SLE-HA 15
- SLE-HA 12

Add site and location to glossary

---

xml/article_geo_clustering.xml
xml/article_installation.xml
xml/ha_concepts.xml
xml/ha_config_basics.xml
xml/ha_configuring_resources.xml
xml/ha_drbd.xml
xml/ha_example_gui_i.xml
xml/ha_fencing.xml
xml/ha_glossary.xml
xml/ha_install.xml
xml/ha_lb_lvs.xml
xml/ha_loadbalancing.xml
xml/ha_maintenance.xml
xml/ha_management.xml
xml/ha_managing_resources.xml
xml/ha_migration.xml
xml/ha_monitoring_clusters.xml
xml/ha_ocfs2.xml
xml/ha_remote_hosts.xml
xml/ha_resource_constraints.xml
xml/ha_storage_protection.xml
xml/ha_troubleshooting.xml
xml/ha_yast_cluster.xml
xml/phrases-decl.ent
xml/product-entities.ent

To correct the productnames to the approved ones as per our terminology database several steps are needed. This is the first step: 
The following preparations were needed before we can fix the value of `&productname;` via doc-kit:
* replace `[T,t]he &hasi;` with `&productname;` where appropriate
* replace `[T,t]he &hasi;` with `&ha; (software)` where appropriate
* jsc#DOCTEAM-1133
- SLE-HA 15
- SLE-HA 12

generic: get rid of outdated &hasi; entity

---

xml/article_pacemaker_remote.xml
xml/ha_acl.xml
xml/ha_configuring_resources.xml
xml/ha_hawk2_history_i.xml
xml/ha_hawk2_monitor_i.xml
xml/ha_ocfs2.xml
xml/ha_resource_constraints.xml

Having figure titles for all images means I can Ctrl-F for "Figure" to check all images that are in use in the doc set. 
I also added descriptions where these were missing for images I added titles to. 
- SLE-HA 15
- SLE-HA 12

Add figure titles to make images easier to find

---

xml/article_installation.xml
xml/ha_storage_protection.xml

Added various advice for using SBD.
* bsc#1202661
* jsc#DOCTEAM-725
- SLE-HA 15
- SLE-HA 12

Add SBD advice from archived TIDs

---

xml/common_intro_convention_ha.xml

As doc-sleha uses its own `common_intro_conventions*.xml` file, propagate the latest changes for `common_intro_conventions.xml` from doc-kit manually.
* see https://github.com/openSUSE/doc-kit/pull/88
- SLE-HA 15
- SLE-HA 12

conventions: latest doc-kit changes

---

xml/ha_configuring_resources.xml
xml/ha_lb_haproxy.xml

A couple of places said `crm configure` where they should, in that particular context, only say `crm`.
* bsc#1218647
* jsc#DOCTEAM-1213
- SLE-HA 15
- SLE-HA 12

Fix crm configure -> just crm where appropriate

---

xml/ha_configuring_resources.xml

Updated this resource example to be correct.
* bsc#1218645
* jsc#DOCTEAM-1212
- SLE-HA 15
- SLE-HA 12

Remove non-existent id param from IPaddr2 example

---

DC-SLE-HA-all
DC-SLE-HA-geo-guide
DC-SLE-HA-geo-quick
DC-SLE-HA-guide
DC-SLE-HA-install-quick
DC-SLE-HA-nfs-quick
DC-SLE-HA-pmremote-quick

This change switches the validation schema from GeekoDoc to DocBook 5.2. This ensures that futures changes of GeekoDoc doesn't affect previous, now unsupported documents.
related to https://gitlab.suse.de/susedoc/docserv-config/-/merge_requests/510
- SLE-HA 15
- SLE-HA 12
no backport necessary

EOL SLE-HA SP1: Switch validation to DocBook 5.2

---

xml/ha_storage_protection.xml

Added the recommended formulas for calculating timeouts for diskless SBD. 
Also added in stonith-timeout since it was missing. Used a number based on what was already there, plus the formulas, but can change all the examples if needed. 
* bsc#1219972
* jsc#DOCTEAM-1289
- SLE-HA 15
- SLE-HA 12

Add formulas for calculating diskless SBD timeouts

---

xml/MAIN.SLEHA.xml
xml/article_geo_clustering.xml
xml/article_installation.xml
xml/article_nfs_storage.xml
xml/article_pacemaker_remote.xml
xml/book_administration.xml
xml/book_geo_clustering.xml
xml/book_quickstarts.xml

* Change version attribute to "5.2"
* Add `<meta name="series">`
* Add `<meta name="task">`
* Add the ITS namespace in root element
n/a
I'm currently unsure if we should cherry-pick it to the maintenance branches. :thinking: 
- SLE-HA 15
- SLE-HA 12

Add metadata for SLE-HA in book & article files

---

xml/article_installation.xml
xml/ha_config_cli.xml
xml/ha_crmreport_passl.xml
xml/ha_hawk2_health_i.xml
xml/ha_hawk2_monitor_i.xml
xml/ha_requirements.xml
xml/ha_troubleshooting.xml
xml/ha_yast_cluster.xml

Added a section on logging in, and other bits and pieces.
* jsc#PED-7399
- SLE-HA 15
- SLE-HA 12

Add info on using --use-ssh-agent

---

xml/article_geo_clustering.xml

Integrate proofing corrections for the Geo Clustering Quick Start from proofing drop 2.
- SLE-HA 15
- SLE-HA 12

Geo Clustering Quick Start: Integrate proofing corrections

---

xml/ha_cluster_lvm.xml

Added a step to make sure VGs are only activated after DLM is already running. 
* bsc#1222440
* jsc#DOCTEAM-1357
- SLE-HA 15
- SLE-HA 12

Add colocation and ordering for clvm

---

xml/ha_migration.xml

In bsc#1224312 we're discussing removing this table and replacing it with a diagram like we have in the SLES upgrade guide. However, because it's still under discussion, I'm adding SP6 to the table for now, just in case. It may end up being redundant, but better there than not. 
* bsc#...
* jsc#...
- SLE-HA 15
- SLE-HA 12

Add SP6 to upgrade paths

---

xml/ha_rear.xml

`rear mkbackup` is only used with the internal backup tool, not with third-party backup tools. These are used separately, in combination with `rear mkrescue`. 
* bsc#1218910
* jsc#DOCTEAM-1243
- SLE-HA 15
- SLE-HA 12

Clarify rear mkbackup vs rear mkrescue

---

xml/ha_iscsi_for_sbd.xml

Noticed some changed steps in the iSCSI procedure while setting up a new test cluster. Not sure when they changed as the SLES Storage guide has the changes all the way back to 12 SP5, but I originally did this procedure based on a 15 SP4 test VM. I guess it doesn't matter :shrug: 
* jsc#DOCTEAM-1459
- SLE-HA 15
- SLE-HA 12

Update iscsi steps

---

xml/ha_cluster_md.xml
xml/phrases-decl.ent

Improved the Cluster MD warning about persistent device names. Added it to the phrases entity file so we can easily reuse it wherever it's needed.
* bsc#1226367
* jsc#DOCTEAM-1466
- SLE-HA 15
- SLE-HA 12

Improve persistent device name warning

---

xml/common_intro_convention_ha.xml
xml/geo_booth_i.xml

Integrate proofing corrections for the Geo Clustering Guide from proofing drop 3.
- SLE-HA 15
- SLE-HA 12

Geo Clustering Guide: integrate proofing corrections

---

xml/ha_storage_protection.xml

Added procedures (disk-based and diskless) for redeploying SBD.  
PDF: 
[cha-ha-storage-protect_en.pdf](https://github.com/user-attachments/files/16022857/cha-ha-storage-protect_en.pdf)
(skip to section 13.11 on page 23)
* bsc#1216632
* jsc#DOCTEAM-1198
- SLE-HA 15
- SLE-HA 12

Add procedures for replacing an SBD disk

---

xml/ha_migration.xml

Clarified a step in the 12 -> 15 upgrade procedure; clvmd -> lvmlockd and cmirrord -> cluster MD are different things.
* bsc#1226518
* jsc#DOCTEAM-1467
- SLE-HA 15
- SLE-HA 12

Clarify clvm step in 12 to 15 upgrade

---

xml/ha_yast_cluster.xml

Passwordless SSH is in the Requirements section, but just in case, I've added a reminder about it in the YaST setup chapter.
* bsc#1219051
* jsc#DOCTEAM-1246
- SLE-HA 15
- SLE-HA 12

Add reminder about passwordless SSH

---

xml/ha_fencing.xml

Some improvements to the text in "Monitoring fencing devices".
* bsc#1219181
* jsc#DOCTEAM-1251
- SLE-HA 15
- SLE-HA 12

Improvements for Monitoring fencing devices

---

xml/article_nfs_storage.xml
xml/ha_drbd.xml

Added fencing config for DRBD. Descriptions are copied from article_nfs_storage.xml.
* bsc#1220064
* jsc#DOCTEAM-1267
- SLE-HA 15
- SLE-HA 12

Add missing DRBD config

---

xml/ha_migration.xml

Update backup recommendations to reflect latest software stack.
no
I think Chrony is the default NTP implementation on all 15 SP's but I'm not fully sure.
- SLE-HA 15
- SLE-HA 12

Back up Chrony instead of legacy NTP configuration

---

xml/ha_qdevice-qnetd.xml

Removed SAP from the QDevice heuristics suggestion, as this hasn't been tested.
* bsc#1228375
* jsc#DOCTEAM-1505
- SLE-HA 15
- SLE-HA 12

Remove SAP from QDevice heuristics suggestion

---

xml/ha_drbd.xml

This procedure used to send you off to three other procedures, which didn't tell you to come back and continue the original one. It was quite confusing. I've restructured it a bit to be easier to follow. 
The old procedure structure:
https://documentation.suse.com/sle-ha/15-SP6/html/SLE-HA-all/cha-ha-drbd.html#sec-ha-drbd-configure
The new procedure structure (starts on page 3): 
[cha-ha-drbd_en.pdf](https://github.com/user-attachments/files/16621903/cha-ha-drbd_en.pdf)
* jsc#DOCTEAM-976
- SLE-HA 15
- SLE-HA 12

Improve the DRBD workflow to be easier to follow

---

xml/ha_rear.xml

Added more examples for creating the ReaR backup config, and improved the section overall. 
PDF: 
[cha-ha-rear_en.pdf](https://github.com/user-attachments/files/16756848/cha-ha-rear_en.pdf) **(Updated Aug 27)**
* bsc#1204927
* jsc#DOCTEAM-787
- SLE-HA 15
- SLE-HA 12

Improve ReaR backup config examples

---

xml/ha_drbd.xml

The steps for resolving a split-brain for DRBD were incorrect. This PR corrects them.
* bsc#1229715
* jsc#DOCTEAM-1550
- SLE-HA 15
- SLE-HA 12

Fix DRBD disconnect steps

---

xml/ha_qdevice-qnetd.xml

I've attempted to make the descriptions of the QDevice/QNetd configuration a bit clearer.
* bsc#1227649
* jsc#DOCTEAM-1497
- SLE-HA 15
- SLE-HA 12

Clarify QDevice/QNetd configuration

---

xml/ha_fencing.xml

Hopefully this makes the fence_kdump example clearer. 
* bsc#1228931
* jsc#DOCTEAM-537
- SLE-HA 15
- SLE-HA 12

Clarify how fence_kdump works

---

xml/ha_samba.xml

Fixed a typo in the Samba chapter
* bsc#1232243
* jsc#DOCTEAM-1620
- SLE-HA 15
- SLE-HA 12

Fix Samba typo

---

xml/ha_cluster_lvm.xml

Added a note stating that lvmlockd with sanlock is not supported.
* bsc#1233762
* jsc#DOCTEAM-1634
- SLE-HA 15
- SLE-HA 12

Add note that lvmlockd with sanlock is not supported

---

xml/article_nfs_storage.xml

Although using an xref to repeat a callout works, the number is included when you copy the screen text. Therefore I'm removing the xref. It's not really necessary anyway. 
* bsc#1234130
* jsc#DOCTEAM-1655
- SLE-HA 15
- SLE-HA 12

Remove unnecessary duplicate callout xref

---

DC-SLE-HA-all
DC-SLE-HA-geo-guide
DC-SLE-HA-geo-quick
DC-SLE-HA-guide
DC-SLE-HA-install-quick
DC-SLE-HA-nfs-quick
DC-SLE-HA-pmremote-quick

This change switches the validation schema from GeekoDoc to DocBook 5.2. This ensures that futures changes of GeekoDoc doesn't affect previous, now unsupported documents.
According to www.suse.com/lifecycle:
* 21 Jul 2020 (FCS)
* 31 Dec 2021 (General Ends)
* 31 Dec 2024 (LTSS Ends)
- SLE-HA 15
- SLE-HA 12
no backport necessary

EOL SLE HA 15 SP2: Switch validation to DocBook 5.2

---

xml/ha_cluster_md.xml

Added a step for cloning and adding constraints for multiple cluster MD devices.
* bsc#1235513
* jsc#DOCTEAM-1660
- SLE-HA 15
- SLE-HA 12

Add step for multiple cluster MD devices

---

xml/ha_glossary.xml

This outdated term wasn't used anywhere else in the HA docs, so I've removed it.
* bsc#1236371
* jsc#DOCTEAM-1681
- SLE-HA 15
- SLE-HA 12

Remove outdated CCM from glossary

---

xml/article_nfs_storage.xml

Added an `op monitor` to the `nfsserver` resource. 
* bsc#1236450
* jsc#DOCTEAM-1682
- SLE-HA 15
- SLE-HA 12

Add op monitor to nfsserver resource

---

xml/article_nfs_storage.xml

Based on PR#429
See also bsc#1231386
* bsc#1231386
* jsc#DOCTEAM-1682
- SLE-HA 15
- SLE-HA 12

Add more op monitors to the NFS guide

---

xml/ha_storage_protection.xml

The timeout step being separate made it seem like an additional thing to do after initialising the device, but `create` overwrites the disk so you wouldn't run it twice. This should, in fact, be another option for step 2. 
I've also changed the example to one of the suggestions from https://www.suse.com/support/kb/doc/?id=000017952
* bsc#1238348
* jsc#DOCTEAM-1718
- SLE-HA 15
- SLE-HA 12

Fix structure of SBD device procedure and example

---

xml/ha_gfs2.xml
xml/ha_ocfs2.xml

Part 1 of the OCFS2 -> GFS2 task for 15 SP7. This PR removes content encouraging the use of OCFS2 over GFS2, and adds a warning that OCFS2 is deprecated.
* jsc#PED-11046
- SLE-HA 15
- SLE-HA 12

Deprecate OCFS2 and fully support GFS2

---

xml/ha_storage_protection.xml

Some small updates to clarify the watchdog timeout for disk-based and diskless SBD. I also added an example for diskless SBD because the formula is a bit different.
See comments below for rendered screen shots.
* bsc#1239818
* jsc#DOCTEAM-1755
- SLE-HA 15
- SLE-HA 12

Clarify SBD watchdog timeout

---

xml/ha_gfs2.xml
xml/ha_ocfs2.xml

Added an example procedure for migrating from OCFS2 to GFS2. I tested this multiple times and it seemed to work, but I was just testing with a couple of text files, not a full volume of cluster data.
See comments for rendered screenshots.
* jsc#PED-11046
- SLE-HA 15
- SLE-HA 12

Add procedure for migrating from OCFS2 to GFS2

---

xml/ha_storage_protection.xml

Added a reference to the SBD man page to help calculate an appropriate value for SBD_DELAY_START.
* bsc#1242942
* jsc#DOCTEAM-1845
- SLE-HA 15
- SLE-HA 12

Add man page for SBD_DELAY_START

---

xml/ha_gfs2.xml

Added the `ro` option to the GFS2 config, since this is what is supported in 15 SP6 and earlier.
* bsc#1241527
* jsc#DOCTEAM-1826
- SLE-HA 15
- SLE-HA 12

Add ro option to GFS2 config

---

xml/ha_cluster_md.xml

Fixed the step/s for adding mdadm.conf to Csync2.
* bsc#1243871
* jsc#DOCTEAM-1869
- SLE-HA 15
- SLE-HA 12

Fix mdadm csync2 steps

---

xml/ha_storage_protection.xml

Based on discussion in bsc#1246622 I've removed the mention of setting `stonith-watchdog-timeout` to a negative value.
* bsc#1246622
* jsc#DOCTEAM-1908
- SLE-HA 15
- SLE-HA 12

Remove note on negative stonith-watchdog-timeout value
